<?php

namespace DoctrineORMModule\Proxy\__CG__\Parents\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ParentsAssoc extends \Parents\Entity\ParentsAssoc implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'datePublished', 'location', 'dateStatus', 'dateNextMeeting', 'meetingStatement', 'meetingTime', 'parentsAssocTeam'];
        }

        return ['__isInitialized__', 'id', 'datePublished', 'location', 'dateStatus', 'dateNextMeeting', 'meetingStatement', 'meetingTime', 'parentsAssocTeam'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ParentsAssoc $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePublished', []);

        return parent::getDatePublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePublished($date_published)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePublished', [$date_published]);

        return parent::setDatePublished($date_published);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStatus', []);

        return parent::getDateStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStatusAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStatusAsString', []);

        return parent::getDateStatusAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateStatus($dateStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateStatus', [$dateStatus]);

        return parent::setDateStatus($dateStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNextMeeting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNextMeeting', []);

        return parent::getDateNextMeeting();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNextMeeting($nextMeetingDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNextMeeting', [$nextMeetingDate]);

        return parent::setDateNextMeeting($nextMeetingDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeetingStatement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeetingStatement', []);

        return parent::getMeetingStatement();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeetingStatement($stmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeetingStatement', [$stmt]);

        return parent::setMeetingStatement($stmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeetingTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeetingTime', []);

        return parent::getMeetingTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeetingTime($meetingTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeetingTime', [$meetingTime]);

        return parent::setMeetingTime($meetingTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentsAssocTeam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentsAssocTeam', []);

        return parent::getParentsAssocTeam();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentsAssocTeamAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentsAssocTeamAsString', []);

        return parent::getParentsAssocTeamAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addToParentsAssocTeam($member)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addToParentsAssocTeam', [$member]);

        return parent::addToParentsAssocTeam($member);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerializeMeeting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerializeMeeting', []);

        return parent::jsonSerializeMeeting();
    }

}
