<?php

namespace DoctrineORMModule\Proxy\__CG__\User\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \User\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'email', 'password', 'status', 'dateCreated', 'passwordResetToken', 'passwordResetTokenCreationDate', '' . "\0" . 'User\\Entity\\User' . "\0" . 'ourTeamMember', '' . "\0" . 'User\\Entity\\User' . "\0" . 'roles', 'newsList', 'eventsList', 'teacherBlogs', 'learningSupportBlogs', 'postsList', 'galleriesList', 'parentsInformationList', 'bookList', 'bookListAuthor', 'schoolLifeList', 'enrolmentList'];
        }

        return ['__isInitialized__', 'id', 'email', 'password', 'status', 'dateCreated', 'passwordResetToken', 'passwordResetTokenCreationDate', '' . "\0" . 'User\\Entity\\User' . "\0" . 'ourTeamMember', '' . "\0" . 'User\\Entity\\User' . "\0" . 'roles', 'newsList', 'eventsList', 'teacherBlogs', 'learningSupportBlogs', 'postsList', 'galleriesList', 'parentsInformationList', 'bookList', 'bookListAuthor', 'schoolLifeList', 'enrolmentList'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusAsString', []);

        return parent::getStatusAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getResetPasswordToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResetPasswordToken', []);

        return parent::getResetPasswordToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetToken', [$token]);

        return parent::setPasswordResetToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordResetTokenCreationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordResetTokenCreationDate', []);

        return parent::getPasswordResetTokenCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordResetTokenCreationDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordResetTokenCreationDate', [$date]);

        return parent::setPasswordResetTokenCreationDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getOurTeamMember()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOurTeamMember', []);

        return parent::getOurTeamMember();
    }

    /**
     * {@inheritDoc}
     */
    public function setOurTeamMember($member)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOurTeamMember', [$member]);

        return parent::setOurTeamMember($member);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getRolesAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolesAsString', []);

        return parent::getRolesAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role]);

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsList', []);

        return parent::getNewsList();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsListAsString', []);

        return parent::getNewsListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addNewsToList($news)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNewsToList', [$news]);

        return parent::addNewsToList($news);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventsList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventsList', []);

        return parent::getEventsList();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventListAsString', []);

        return parent::getEventListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addEventToList($event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEventToList', [$event]);

        return parent::addEventToList($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getTecherBlogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTecherBlogs', []);

        return parent::getTecherBlogs();
    }

    /**
     * {@inheritDoc}
     */
    public function getTeacherBlogsAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeacherBlogsAsString', []);

        return parent::getTeacherBlogsAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addTeacherBlog($blog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTeacherBlog', [$blog]);

        return parent::addTeacherBlog($blog);
    }

    /**
     * {@inheritDoc}
     */
    public function getLearningSupportBlogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLearningSupportBlogs', []);

        return parent::getLearningSupportBlogs();
    }

    /**
     * {@inheritDoc}
     */
    public function getLearningSupportBlogsAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLearningSupportBlogsAsString', []);

        return parent::getLearningSupportBlogsAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addLearningSupportBlog($blog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLearningSupportBlog', [$blog]);

        return parent::addLearningSupportBlog($blog);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostsList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostsList', []);

        return parent::getPostsList();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostsListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostsListAsString', []);

        return parent::getPostsListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addPostToList($post)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPostToList', [$post]);

        return parent::addPostToList($post);
    }

    /**
     * {@inheritDoc}
     */
    public function getGalleriesList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGalleriesList', []);

        return parent::getGalleriesList();
    }

    /**
     * {@inheritDoc}
     */
    public function getGalleriesListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGalleriesListAsString', []);

        return parent::getGalleriesListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addGalleryPostToList($galleryPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGalleryPostToList', [$galleryPost]);

        return parent::addGalleryPostToList($galleryPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentsInformationList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentsInformationList', []);

        return parent::getParentsInformationList();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentsInformationListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentsInformationListAsString', []);

        return parent::getParentsInformationListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addParentsInformationToList($parentsInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParentsInformationToList', [$parentsInformation]);

        return parent::addParentsInformationToList($parentsInformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookList', []);

        return parent::getBookList();
    }

    /**
     * {@inheritDoc}
     */
    public function getBookListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookListAsString', []);

        return parent::getBookListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addBookListToList($bookList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBookListToList', [$bookList]);

        return parent::addBookListToList($bookList);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookListAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookListAuthor', []);

        return parent::getBookListAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function getBookListAuthorAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookListAuthorAsString', []);

        return parent::getBookListAuthorAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addBookListAuthorToList($bookList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBookListAuthorToList', [$bookList]);

        return parent::addBookListAuthorToList($bookList);
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolLifeList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolLifeList', []);

        return parent::getSchoolLifeList();
    }

    /**
     * {@inheritDoc}
     */
    public function getSchoolLifeListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSchoolLifeListAsString', []);

        return parent::getSchoolLifeListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addSchoolLifeToList($schoolLife)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSchoolLifeToList', [$schoolLife]);

        return parent::addSchoolLifeToList($schoolLife);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnrolmentList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnrolmentList', []);

        return parent::getEnrolmentList();
    }

    /**
     * {@inheritDoc}
     */
    public function getEnrolmentListAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnrolmentListAsString', []);

        return parent::getEnrolmentListAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function addEnrolmentToList($enrolment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEnrolmentToList', [$enrolment]);

        return parent::addEnrolmentToList($enrolment);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
