<?php
// module/Album/view/application/index/addnews.phtml:

$headTitle = 'Add new album';
$this->headTitle($headTitle);
?>
<h1><?= $this->escapeHtml($headTitle) ?></h1>
<?php
$form->setAttribute('action', $this->url('application', ['action' => 'addnews']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('content'));
echo $this->formRow($form->get('imgurl'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();



