<?php
$headTitle = 'Add newsletter';
$this->headTitle($headTitle);
?>
<h1><?= $this->escapeHtml($headTitle) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Newsletter title');

$file_name = $form->get('file_name');
$file_name->setAttribute('class', 'form-control');
$file_name->setAttribute('placeholder', 'Add file');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('application', ['action' => 'addnewsletter']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>
<div class="form-group">
    <?= $this->formLabel($file_name) ?>
    <?= $this->formElement($file_name) ?>
    <?= $this->formElementErrors()->render($file_name, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
