<?php
/*
 * Function requested by Ajax
 */
if(isset($_POST['func']) && !empty($_POST['func'])){
	switch($_POST['func']){
		case 'getCalender':
			getCalender($_POST['year'],$_POST['month']);
			break;
		case 'getEvents':
			getEvents($_POST['date']);
			break;
		default:
			break;
	}
}

/*
 * Get calendar full HTML
 */
function getCalender($year = '',$month = '',$day = '')
{
	$dateYear = ($year != '')?$year:date("Y");
	$dateMonth = ($month != '')?$month:date("m");
	$dateDay = ($day != '')?$day:date("d");
	$date = $dateYear.'-'.$dateMonth.'-01';
	$currentMonthFirstDay = date("N",strtotime($date));
	$totalDaysOfMonth = cal_days_in_month(CAL_GREGORIAN,$dateMonth,$dateYear);
	$totalDaysOfMonthDisplay = ($currentMonthFirstDay == 7)?($totalDaysOfMonth):($totalDaysOfMonth + $currentMonthFirstDay);
	$boxDisplay = ($totalDaysOfMonthDisplay <= 35)?35:42;
?>

	<div id="calendar-page" >
		<?php
			// var for presentation
			$today = date("d M Y",strtotime("now"));
			$dayofweek = date('l', strtotime("now"));
			
			// Check number of events today
				include 'dbConfig.php';
				//Get events based on the current date (date format consistent with DB)
				$result = $db->query("SELECT * FROM events WHERE date = '".date('Y-m-d', strtotime("now"))."' AND status = 1");
				//Number of events from result
				$rowcount=mysqli_num_rows($result);
			
			
			// Header - current date
			echo '<div class="current_date">Today is ' .$dayofweek.', '.$today.'</div>';
			echo '<hr class="orange">';
			
			echo '<div id="event_list">';
				echo '<img src="resources/img/main/icon-paper-pin.png">';
				
				if($rowcount > 0){
					echo '<div class="event_header">Today\'s events list</div>';
					
					echo '<ul>';
						while($row = $result->fetch_assoc()){
							echo '<li>';
								echo '<div class="event_wrapper">';
									echo '<span class="event-title">';
									
									$eventTitle = $row['title'];
									//TODO pass object Event in data-modal
									echo '<a href="#" class="modal-trigger bs" data-modal="'.$eventTitle.'">';
										echo '<span class="space-10">#</span>'.$eventTitle;	
									echo '</a>';	

									echo '</span>';
								echo '</div>';
							echo '</li>';
						}
					echo '</ul>';		
				}else{
					echo '<div class="event_header">No events<br>'.$dayofweek.', '.$today.'</br><img src="resources/img/main/icon-no-events2.png"></div>';
				}
				
			echo '</div>';
		?>
	</div>

	<div id="calender_section">
            <h2>
        	<a href="javascript:void(0);" onclick="getCalendar('calendar_div','<?php echo date("Y",strtotime($date.' - 1 Month')); ?>','<?php echo date("m",strtotime($date.' - 1 Month')); ?>');"><i class="fa fa-angle-double-left" aria-hidden="true"></i></a>
                <select name="month_dropdown" class="month_dropdown dropdown"><?php echo getAllMonths($dateMonth); ?></select>
		<select name="year_dropdown" class="year_dropdown dropdown"><?php echo getYearList($dateYear); ?></select>
                <a href="javascript:void(0);" onclick="getCalendar('calendar_div','<?php echo date("Y",strtotime($date.' + 1 Month')); ?>','<?php echo date("m",strtotime($date.' + 1 Month')); ?>');"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
            </h2>
		
		<div id="calender_section_top">
			<ul>
				<li>Sun</li>
				<li>Mon</li>
				<li>Tue</li>
				<li>Wed</li>
				<li>Thu</li>
				<li>Fri</li>
				<li>Sat</li>
			</ul>
		</div>
		<div id="calender_section_bot">
			<ul>
			<?php 
				$dayCount = 1; 
				for($cb=1;$cb<=$boxDisplay;$cb++){
					if(($cb >= $currentMonthFirstDay+1 || $currentMonthFirstDay == 7) && $cb <= ($totalDaysOfMonthDisplay)){
						//Current date
						$currentDate = $dateYear.'-'.$dateMonth.'-'.$dayCount;
						$eventNum = 0;
						//Include db configuration file
						include 'dbConfig.php';
						//Get number of events based on the current date
						$result = $db->query("SELECT title FROM events WHERE date = '".$currentDate."' AND status = 1");
						$eventNum = $result->num_rows;
						//Define date cell color
						if(strtotime($currentDate) == strtotime(date("Y-m-d"))){
							echo '<a href="javascript:;" onclick="getEvents(\''.$currentDate.'\');">';
							echo '<li date="'.$currentDate.'" class=" date_cell">';
							//Date cell
							echo '<div class="today"><span>';
							echo $dayCount;
							echo '</span></div>';
						}elseif($eventNum > 0){
							echo '<a href="javascript:;" onclick="getEvents(\''.$currentDate.'\');">';
							echo '<li date="'.$currentDate.'" class="date_cell">';
							//Date cell
							echo '<div class="events"><span>';
							echo $dayCount;
							echo '</span></div>';
							
						}else{
							echo '<a href="javascript:;" onclick="getEvents(\''.$currentDate.'\');">';
							echo '<li date="'.$currentDate.'" class="date_cell">';
							//Date cell
							echo '<div><span>';
							echo $dayCount;
							echo '</span></div>';
						}
						/* //Date cell
						echo '<span>';
						echo $dayCount;
						echo '</span>'; */
						
						//Hover event popup
						if($eventNum > 0){	//dodane zeby nie wyswietlalo okna gdzie nie ma eventu
							 /* echo '<span class="events_number">Events: '.$eventNum.'</span>';  */
							/* echo '<span class="events_number"><img src="resources/img/main/icon-check1.png"></span>'; */
							echo '<span class="events_number">'.$eventNum.'</span>';
						}
						
						echo '</li>';
						echo '</a>';
						
						$dayCount++;
						
						//Hover event popup
						/* echo '<div id="date_popup_'.$currentDate.'" class="date_popup_wrap none">';
						echo '<div class="date_window">';
						echo '<div class="popup_event">Events ('.$eventNum.')</div>';
						echo ($eventNum > 0)?'<a href="javascript:;" onclick="getEvents(\''.$currentDate.'\');">view events</a>':'';
						echo '</div></div>';
						
						echo '</li>';
						$dayCount++; */
			?>
			<?php }else{ ?>
				<li><span>&nbsp;</span></li>
			<?php } } ?>
			</ul>
		</div>
	</div>

	<script type="text/javascript">
		function getCalendar(target_div,year,month){
			$.ajax({
				type:'POST',
				url:'calendar.php',
				data:'func=getCalender&year='+year+'&month='+month,
				success:function(html){
					$('#'+target_div).html(html);
				}
			});
		}
		
		function getEvents(date){
			$.ajax({
				type:'POST',
				url:'calendar.php',
				data:'func=getEvents&date='+date,
				success:function(html){
					$('#event_list').html(html);
					$('#event_list').slideDown('slow');
				}
			});
		}
		
		/* function addEvent(date){
			$.ajax({
				type:'POST',
				url:'calendar.php',
				data:'func=addEvent&date='+date,
				success:function(html){
					$('#event_list').html(html);
					$('#event_list').slideDown('slow');
				}
			});
		} */
		
		$(document).ready(function(){
			$('.date_cell').mouseenter(function(){
				date = $(this).attr('date');
				$(".date_popup_wrap").fadeOut();
				$("#date_popup_"+date).fadeIn(10000);	
			});
			$('.date_cell').mouseleave(function(){
				$(".date_popup_wrap");		
			});
			$('.month_dropdown').on('change',function(){
				getCalendar('calendar_div',$('.year_dropdown').val(),$('.month_dropdown').val());
			});
			$('.year_dropdown').on('change',function(){
				getCalendar('calendar_div',$('.year_dropdown').val(),$('.month_dropdown').val());
			});
			$(document).click(function(){
				$('#event_list');
				/* $('#event_list').slideUp('slow'); */
			});

		});
	</script>
<?php
}

/*
 * Get months options list.
 */
function getAllMonths($selected = ''){
	$options = '';
	for($i=1;$i<=12;$i++)
	{
		$value = ($i < 10)?'0'.$i:$i;
		$selectedOpt = ($value == $selected)?'selected':'';
		$options .= '<option value="'.$value.'" '.$selectedOpt.' >'.date("F", mktime(0, 0, 0, $i+1, 0, 0)).'</option>';
	}
	return $options;
}

/*
 * Get years options list.
 */
function getYearList($selected = ''){
	$options = '';
	for($i=2015;$i<=2035;$i++)
	{
		$selectedOpt = ($i == $selected)?'selected':'';
		$options .= '<option value="'.$i.'" '.$selectedOpt.' >'.$i.'</option>';
	}
	return $options;
}

/*
 * Get events number from date.
 */
function getEventsNumber($date = ''){
	
	$dateNow = date('Y-m-d', strtotime("now"));
	include 'dbConfig.php';
	
	//Get events based on the current date
	$result = $db->query("SELECT * FROM events WHERE date = '".$dateNow."' AND status = 1");
	//Number of events from result
	$rowcount=mysqli_num_rows($result);
	
	return $rowcount;
}

/*
 * Get events by date
 */
function getEvents($date = ''){
	$currentDate = date('d-m-Y');
	//Include db configuration file
	include 'dbConfig.php';
	$eventListHTML = '';
	$date = $date?$date:date("d M Y");
	$dayofweek = date('l', strtotime($date));
	//Get events based on the current date
	$result = $db->query("SELECT * FROM events WHERE date = '".$date."' AND status = 1");
	//Number of events from result
	$rowcount=mysqli_num_rows($result);
	if($result->num_rows > 0){
		$eventListHTML .= '<img src="resources/img/main/icon-paper-pin.png">';
		/* $eventListHTML = '<div class="current_date">
        					Today is <br>'.$currentDate.'<br></div>'; */
       /*  if($rowcount == 1){ */
        	
        	$eventListHTML .= '<div class="event_header">Events list <br>'.$dayofweek.', '.date("d M Y",strtotime($date)).'</div>';
       /*  }else{	 */			
        				
			/* $eventListHTML .= '<div class="event_header">'.date("l, d M Y",strtotime($date)).'</div>'; */
       /*  } */
		/* $eventListHTML = '<div class="events">'.$rowcount.' events '.date("l, d M Y",strtotime($date)).'</div>'; */
		$eventListHTML .= '<ul>';
		while($row = $result->fetch_assoc()){
			$eventTitle = $row['title'];
            /* $eventListHTML .= '<li><div class="event_img"><img src="data:image/jpeg;base64,'.base64_encode( $row['img'] ).'"/></div>
									<div class="event_wrapper">
										<span class="event-title">'.$row['title'].'<br></span><span class="event-text">'.$row['text'].'</span>
        							</div>
        						</li>'; */
			$eventListHTML .= '<li>
									<div class="event_wrapper">
										<span class="event-title">
        			
									
									<a href="#" class="modal-trigger bs" data-modal="'.$eventTitle.'">
										<span class="space-10">#</span>'.$eventTitle.'	
									</a>	
        			
        			

            							</span>
        							</div>
        						</li>';
        }
		$eventListHTML .= '</ul>';
	}else{
		$eventListHTML .= '<img src="resources/img/main/icon-paper-pin.png">';
		/* $eventListHTML = '<div class="current_date">
        					Today is <br>'.$currentDate.'<br></div>'; */
		
        /* $eventListHTML .= '<div class="event_header no-events">'.date("l, d M Y",strtotime($date)).'</br>No events</div>'; */
        $eventListHTML .= '<div class="event_header">No events<br>'.$dayofweek.', '.date("d M Y",strtotime($date)).'</br><img src="resources/img/main/icon-no-events2.png"></div>';
        
	} 
	echo $eventListHTML;
}


?>

<script type="text/javascript">
/* JS for MODAL event from yellow calendar page */
 $(".modal-trigger").click(function(e){
	  e.preventDefault();
	  dataModal = $(this).attr("data-modal");
	  $("#" + dataModal).css({"display":"block"});
	});

	$(".close-modal, .close-modal-btn, .modal-sandbox").click(function(){
	  $(".modal").css({"display":"none"});
	});
</script>