<?php


// module/Application/view/application/index/deletenews.phtml:

$headTitle = 'Delete news';
$url   = $this->url('application', ['action' => 'deletenews', 'id' => $id]);

$this->headTitle($headTitle);
?>
<h1><?= $this->escapeHtml($headTitle) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($news->title) ?>" by
    "<?= $this->escapeHtml($news->content) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $news->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>

