<?php
// module/Album/view/application/index/editAboutUs.phtml:

$headTitle = 'Edit About us';
$this->headTitle($headTitle);
?>
<h1><?= $this->escapeHtml($headTitle) ?></h1>
<?php
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Title');

$content = $form->get('content');
$content->setAttribute('class', 'form-control');
$content->setAttribute('rows', '20');
$content->setAttribute('placeholder', 'About us - content');

$principal_name = $form->get('principal_name');
$principal_name->setAttribute('class', 'form-control');
$principal_name->setAttribute('placeholder', 'Title');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('application', ['action' => 'editaboutus', 'id' => $id,]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($content) ?>
    <?= $this->formElement($content) ?>
    <?= $this->formElementErrors()->render($content, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($principal_name) ?>
    <?= $this->formElement($principal_name) ?>
    <?= $this->formElementErrors()->render($principal_name, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
