<?php
// module/Album/view/application/index/editWelcomeMsg.phtml:

$headTitle = 'Edit Welcome message';
$this->headTitle($headTitle);
?>
<h1><?= $this->escapeHtml($headTitle) ?></h1>
<?php
$content = $form->get('content');
$content->setAttribute('class', 'form-control');
$content->setAttribute('rows', '20');
$content->setAttribute('placeholder', 'First paragraph');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('application', ['action' => 'editwelcomemsg', 'id' => $id,]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($content) ?>
    <?= $this->formElement($content) ?>
    <?= $this->formElementErrors()->render($content, ['class' => 'help-block']) ?>
</div>



<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

