<?php

/*
 *  Our team - index
 */
$current_season = $this->layout()->currenSeason->getSeasonName();
$this->headTitle($this->headTitle);

?>

<!-- // PARENTS SECTION -->
<section class="our-team">
    <!-- SECTION HEADER -->
    <div class="header">
	<div class="baner">
            <img src="img/our-team/banner.jpg" />
	</div>
	<div class="header-title reverse">Our Team</div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube2 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube4 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-06s"></div>
	</div>
    </div>

    <div class="our-team-box">
	<div class="main-col-left">
            
            <div class="teachers-box">
                <div class="title blue">Teachers</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option teachers">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-teacher-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Manage the list of teachers</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->teacherList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users blue">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users blue modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" >';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
            <div class="learning-support-box">
                <div class="title purpure">Learning support</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option learning-support">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-learning_support-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Manage the list of learning support members</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->learningSupportList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users purpure">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users purpure modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" >';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
            <div class="secretary-box">
                <div class="title orange">Secretary</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option secretary">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-secretary-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Change Secretary</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->secretaryList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users orange">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users orange modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" >';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
	</div>
        
        <div class="main-col-right">
            
            
            
            
            <div class="principal-box">
                <div class="title burgundy">Principal</div>
                <?php 
                    if ($this->access('ourteam.manage')) {

                        echo '<div class="cms-option our-team">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-principal-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>change principal</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->principalList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users burgundy">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users burgundy modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'">';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
            <div class="management-box">
                <div class="title orange">Board of Management</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option board-of-management">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-management-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Change board of management</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->managementList as $member){
                            echo '<li>';
                                echo '<img src="/img/icons/icon-arrow-right-fat.png">';
                                echo ' <span class="our-team-role">'.$member->getManagementRoleAsString().'</span> - <span>'.$member->getFirstNameLastName().'</span>';
                            echo  '</li>';
                        }
                    ?>
                </ul>
            </div>
            <div class="sna-box">
                <div class="title red">SNA</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option sna">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-sna-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Change sna list</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->snaList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users red">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users red modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'">';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
            <div class="asd-unit-box">
                <div class="title yellow">ASD Unit</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option asdunit">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-asd_unit-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Change asd unit list</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->asdUnitList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users yellow">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users yellow modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'">';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
            
            <div class="caretaker-box">
                <div class="title brown">Caretaker</div>
                <?php 
                    if ($this->access('ourteam.manage')) {
                        echo '<div class="cms-option caretaker">';
                            echo '<a href="#" class="bs modal-trigger" data-modal="manage-caretaker-modal">';
                                echo '<img src="img/icons/icon-settings.png">';
                                echo '<span>Change caretaker</span>';
                            echo '</a>';
                        echo '</div>';
                    }     
                ?>
                <ul>
                    <?php
                        foreach($this->caretakerList as $member){
                            if($member->getStatus()== 1){
                                echo '<li>';
                                    echo '<img src="/img/icons/icon-arrow-right-fat.png">';

                                    if ($this->identity() == null) {
                                        echo '<span>'.$member->getFullName().'</span>';
                                    }else{
                                        if($member->getUser() !== null){
                                            echo '<a href="'.$this->url('user', ['action'=>'view', 'id'=>$member->getUser()->getId()]).'" class="bs users brown">';
                                                echo '<span>'.$member->getFullName().'</span>';
                                            echo '</a>';
                                        }else{
                                            if ($this->access('user.add')) {
                                                echo '<a href="#" class="bs users brown modal-trigger-create-account" data-modal="create-account-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'">';
                                                    echo '<span>'.$member->getFullName().'</span>';
                                                echo '</a>';
                                            }else{
                                                echo '<span>'.$member->getFullName().'</span>';
                                            }                                
                                        }           
                                    }

                                echo  '</li>';
                            }
                        }
                    ?>
                </ul>
            </div>
	</div>
    </div><!-- our-team-box -->
</section>


<!-- Manage Principal Modal -->
<div class="modal" id="manage-principal-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - Principal</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-burgundy reversed" data-modal="add-our-team" data-role="principal" data-text="Add principal">
                    <span><i class="fa fa-plus"></i>Add principal</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">Principal</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->principalList as $member){
                        
                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="principal">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) {                                    
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="principal">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Principal Modal -->


<!-- Manage Board of managment Modal -->
<div class="modal" id="manage-management-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Board of Management</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-orange reversed" data-modal="add-our-team" data-role="management" data-text="Add Member of the Board">
                    <span><i class="fa fa-plus"></i>Add Member of the Board</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">List of members</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->managementList as $member){

                        echo '<div class="our-team-table-row">';
                            echo '<div class="our-team-table-cell role">';
                                echo '<span>'.$member->getManagementRoleAsString().'</span>';

                            echo '</div>';
                            echo '<div class="our-team-table-cell management-full-name">';
                                echo '<span>'.$member->getFirstNameLastName().'</span>';

                            echo '</div>';
                            echo '<div class="our-team-table-cell edit">';
                                if ($this->access('ourteam.manage')) {
                                    //
                                 }                               
                            echo '</div>';

                            echo '<div class="our-team-table-cell remove">';
                                if ($this->access('ourteam.manage')) {
                                    echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="management">';
                                        echo '<button class="btn-admin">';
                                            echo '<img class="icon-list" src="img/icons/icon-bin-red.png" >';
                                        echo '</button>';
                                        echo '<span class="tooltiptext remove">Remove</span>';
                                    echo '</a>';
                                }

                            echo '</div>';

                        echo '</div>';

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Board of managment Modal -->


<!-- Manage Teacher Modal -->
<div class="modal" id="manage-teacher-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - Teachers</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-blue reversed" data-modal="add-our-team" data-role="teacher" data-text="Add teacher">
                    <span><i class="fa fa-plus"></i>Add teacher</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">List of teachers</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->teacherList as $member){
                        
                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="teacher">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="teacher">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Teacher Modal -->

<!-- Manage Learning Support Modal -->
<div class="modal" id="manage-learning_support-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - Learning Support</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-purpure reversed" data-modal="add-our-team" data-role="learning_support" data-text="Add member of learning support">
                    <span><i class="fa fa-plus"></i>Add member of learning support</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">Members of learning support</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->learningSupportList as $member){
                        
                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="learning_support">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="learning_support">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Learning Support Modal -->

<!-- Manage Secretary Modal -->
<div class="modal" id="manage-secretary-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - Secretary</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-orange reversed" data-modal="add-our-team" data-role="secretary" data-text="Add secretary">
                    <span><i class="fa fa-plus"></i>Add secretary</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">Secretary</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->secretaryList as $member){

                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="secretary">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) { 
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="secretary">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Secretary Modal -->


<!-- Manage SNA Modal -->
<div class="modal" id="manage-sna-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - SNA</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-red reversed" data-modal="add-our-team" data-role="sna" data-text="Add member of sna">
                    <span><i class="fa fa-plus"></i>Add member of sna</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">Members of SNA</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->snaList as $member){
                        
                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="sna">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="sna">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage SNA Modal -->


<!-- Manage ASD Unit  Modal -->
<div class="modal" id="manage-asd_unit-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - ASD Unit</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-yellow reversed" data-modal="add-our-team" data-role="asd_unit" data-text="Add member of asd unit">
                    <span><i class="fa fa-plus"></i>Add member of asd unit</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">Members of ASD Unit</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->asdUnitList as $member){
                        
                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="asd_unit">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="asd_unit">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage ASD Unit Modal -->


<!-- Manage Caretaker  Modal -->
<div class="modal" id="manage-caretaker-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our team - Caretaker</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-team btn-max btn-brown reversed" data-modal="add-our-team" data-role="caretaker" data-text="Add caretaker">
                    <span><i class="fa fa-plus"></i>Add caretaker</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">Caretaker</div>
            <div class="our-team-table">    
                <?php 
                    foreach($this->caretakerList as $member){
                        

                        if($member->getStatus() == 1){
                            echo '<div class="our-team-table-row">';

                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';

                                if($member->getUser() != null){
                                    echo '<div class="our-team-table-cell edit">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/edit/'.$member->getUser()->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-edit-blue.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext edit">Edit member</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }else{
                                    echo '<div class="our-team-table-cell create-account">';
                                        if ($this->access('ourteam.manage')) {
                                            echo '<a href="/user/addaccount/'.$member->getId().'" class="tooltip">';
                                                echo '<button class="btn-admin">';
                                                    echo '<img class="icon-list" src="img/icons/icon-settings.png" >';
                                                echo '</button>';
                                                echo '<span class="tooltiptext create-account">Create account</span>';
                                            echo '</a>';
                                         }                               
                                    echo '</div>';
                                }
                                echo '<div class="our-team-table-cell disable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-our-team" data-modal="delete-our-team-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="caretaker">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-disable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext disable">Deactivate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';

                            echo '</div>';
                        }else{
                            echo '<div class="our-team-table-row member-disable">';
                                echo '<div class="our-team-table-cell full-name">';
                                    echo '<span>'.$member->getFullName().'</span>';
                                echo '</div>';
                                
                                echo '<div class="our-team-table-cell edit"></div>';
                                
                                
                                echo '<div class="our-team-table-cell enable">';
                                    if ($this->access('ourteam.manage')) {
                                        echo '<a href="#" class="tooltip modal-trigger-activate-our-team-member" data-modal="activate-our-team-member-modal" data-memberID="'.$member->getId().'" data-memberFullName="'.$member->getFullName().'" data-type="caretaker">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-enable.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext enable">Activate member</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                                
                            echo '</div>';
                        }

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Caretaker Modal -->



<!-- Add Our Team Member Modal-->
<div class="modal" id="add-our-team">
    <div class="modal-sandbox"></div>
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="add-pa-member" src="/../img/icons/icon-add-user.png" alt="" /></div>

            
            <!-- original version -->
            <div class="modal-title">
                <span>Add</span><span id="add-role-type"></span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="addOurTeamForm" class="cms" enctype="multipart/form-data"> 
                    
                    <input type="hidden" id="addOurTeamType" name="addOurTeamType" required/>
                    
                    <div class='width-30-left'>
                        <label id="addOurTeamTitleLabel">Title:</label>
                        <select id="addOurTeamTitleSelect" name="addOurTeamTitleSelect" class="dropdown">
                            <option value="0">--- SELECT ---</option>
                            <option value="1">Mr.</option>
                            <option value="2">Mrs.</option>
                            <option value="3">Ms.</option>
                        </select>
                    </div>
                    
                    <div class='width-65-right' id="management-select-list">
                        
                    </div>
                    
                    
                    <div class='width-100'>
                        <label id="addOurTeamFirstNameLabel">First name:</label>
                        <input type="text" id="addOurTeamFirstName" name="addOurTeamFirstName">
                    </div>
                    
                     <div class='width-100'>
                        <label id="addOurTeamLastNameLabel">Last name:</label>
                        <input type="text" id="addOurTeamLastName" name="addOurTeamLastName">
                    </div>

             
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left medium" data-text="Add memeber"><span>Add memeber</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right medium" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
                
     
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Add Our Team Member Modal-->






<!-- Deactivate Our Team member Modal-->
<div class="modal" id="delete-our-team-modal">
    <div class="modal-sandbox"></div>
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper"><img class="events" src="/../img/icons/icon-disable.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Deactivate member</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-our-team-deactivate'>You really want to deactivate <span></span> ?</div>
                <form id="deleteOurTeamForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deleteOurTeamID" name="deleteOurTeamID" required>
                    <input type="hidden" id="deleteOurTeamType" name="deleteOurTeamType" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end Deactivate Our Team member Modal -->

<!-- Activate Our Team member Modal-->
<div class="modal" id="activate-our-team-member-modal">
    <div class="modal-sandbox"></div>
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper"><img class="events" src="/../img/icons/icon-enable.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Activate member</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-our-team-activate'>You really want to activate <span></span> ?</div>
                <form id="activateOurTeamForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="activateOurTeamID" name="activateOurTeamID" required>
                    <input type="hidden" id="activateOurTeamType" name="activateOurTeamType" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end Enable Our Team member Modal -->


<!-- Create Our Team Account Modal-->
<div class="modal" id="create-account-modal">
    <div class="modal-sandbox"></div>
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper"><img class="events" src="/../img/icons/icon-add-user.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Create Account</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <div class='create-account-question'><span id='newAccountFullName'></span><span class='question'>Do you want to create it now?</span></div>
                
                <div class="btn-modal-box">
                    <a href="" id='new-member-account'>
                        <button type="button" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                    </a>
                    <button type="button" onClick="window.location.reload()" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                </div>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end Our Team member Modal -->







<script src="/js/our-team-add.js" type="text/javaScript"></script>
<script src="/js/our-team-delete.js" type="text/javaScript"></script>
<script src="/js/our-team-activate.js" type="text/javaScript"></script>
<script src="/js/create-account-passer.js" type="text/javaScript"></script>








