<?php // in module/Classes/view/partial/paginator.phtml: ?>
<?php if ($this->pageCount): ?>
<div class="pagination-wrapper">
<!--  <ul class="pagination">-->
  <!-- Previous page link -->
<div class="pagination full-page">
  <?php if (isset($this->previous)): ?>
    <div class="previous">   
      <a href="<?= $this->url($this->route, ['id' => $this->id, 'color' => $this->color], ['query' => ['page' => $this->previous]]) ?>">
          <button type="button" class="btn-pagination btn-burgundy lg" data-text="Previous"><span>Previous</span></button>
      </a>
    </div>
  <?php else: ?>
    <div class="previous">
        <button type="button" class="btn-paginationbtn-grey lg"></button>
    </div>
  <?php endif ?>

<div class="pages">
  <!-- Numbered page links -->
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page !== $this->current): ?>
      <div class="page">
        <a href="<?= $this->url($this->route, ['id' => $this->id, 'color' => $this->color], ['query' => ['page' => $page]]) ?>">
            <button type="button" class="btn-pagination btn-burgundy" data-text="<?= $page ?>"><span><?= $page ?></span></button>
        </a>
      </div>
    <?php else: ?>
      <div class="page">
        <a href="#">
            <button type="button" class="btn-pagination btn-burgundy active" data-text="<?= $page ?>"><span><?= $page ?></span></button>
        </a>
      </div>
    <?php endif ?>
  <?php endforeach ?>
</div>
  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <div class="next">
      <a href="<?= $this->url($this->route, ['id' => $this->id, 'color' => $this->color], ['query' => ['page' => $this->next]]) ?>">
        <button type="button" class="btn-pagination btn-burgundy lg" data-text="Next"><span>Next</span></button>  
      </a>
    </div>
  <?php else: ?>
    <div class="next">
        <button type="button" class="btn-paginationbtn-grey lg"></button>
    </div>
  <?php endif ?>
<!--  </ul>-->
</div>
</div>
<?php endif ?>

