<?php 
$this->headTitle($this->title);
?>


<section class="admin">
    
    <div class="header">
        <div class="header-title reverse"><i class="fa fa-ban" aria-hidden="true"></i><?= $this->escapeHtml($this->title) ?></div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube4 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-06s"></div>
	</div>
    </div>
    
    
    
    <div class='admin-box'>
        <div class='not-authorized'>
            <img src="/../img/icons/icon-stop.png">
            <span>Sorry, you have no permission to see this page.</span>
        </div>   
    </div>
    
</section>

