<?php
 
$this->headTitle($this->title);

$form->setAttributes(['class'=>'cms']);

$form->get('email')->setAttributes([
    'class'=>'form-control',
    ]);

$form->get('title')->setAttributes([
    'class'=>'form-control dropdown'
    ]);

$form->get('first_name')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('last_name')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control dropdown'
    ]);

$form->get('roles')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn-about-us btn-burgundy']);

$form->prepare();

?>

<section class="admin">
    <div class="header">
        <div class="header-title reverse"><i class="fa fa-user-circle-o" aria-hidden="true"></i><?= $this->escapeHtml($this->title) ?></div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube4 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-06s"></div>
	</div>
    </div>
    
    <div class='admin-box'>
        
        
        <div class='form-wrapper-header'>
            To update data for <span class='member-name'>
            <?= $this->user->getOurTeamMember()->getFullName() ?></span>, please change the details in the form below and click <span>"Edit"</span>    
        </div>
        
        <div class='form-wrapper'>
            <?= $this->form()->openTag($form); ?>
            
                <?= $this->formLabel($form->get('title')); ?>
                <?= $this->formElement($form->get('title')); ?>
                <?= $this->formElementErrors($form->get('title')); ?>
            
                <?= $this->formHidden($form->get('first_name')); ?>
                <?= $this->formElement($form->get('first_name')); ?>
                <?= $this->formElementErrors($form->get('first_name')); ?>
            
                <?= $this->formLabel($form->get('last_name')); ?>
                <?= $this->formElement($form->get('last_name')); ?>
                <?= $this->formElementErrors($form->get('last_name')); ?>
            
                <?= $this->formHidden($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
            
            
            <!-- admin only but NOT my own -->
            <?php if ($this->access('user.edit') && !$this->access('user.own.edit', ['user'=>$user])) { ?>
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            <?php }else{ ?>
                <?= $this->formHidden($form->get('email')); ?>
                <?= $this->formElement($form->get('email')->setAttributes(['hidden'=>true])); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            <?php } ?>
            
            <!-- how to change email address info (in case you are ADMIN and you want to change your own address) -->
            <?php if ($this->access('user.edit') && $this->access('user.own.edit', ['user'=>$user])) { ?>
                <div class='form-wrapper-form-info'>
                    To change the email address, contact the person who is the system ADMIN.</br>
                    Ask another administrator to change your email address <b>(you can not change your own email address).</b>
                </div>
            <?php } ?>
            <!-- how to change email address info (in case you are NOT ADMIN and you want to change your own address)  -->
            <?php if (!$this->access('user.edit') && $this->access('user.own.edit', ['user'=>$user])) { ?>
                <div class='form-wrapper-form-info'>
                    To change the email address, contact the person who is the system ADMIN.</br>
                </div>
            <?php } ?>
            
            
            <!-- admin only -->
            <?php if ($this->access('user.edit')) { ?>
                <?= $this->formLabel($form->get('roles')); ?>
                <?= $this->formElement($form->get('roles')); ?>
                <?= $this->formElementErrors($form->get('roles')); ?> 
            <?php }else{?>
                <!-- important id for label hidde multicheckbox labels (ref to css file) -->
                <?= $this->formLabel($form->get('roles')->setLabelAttributes([ 'id' => "hiddenMulticheckbox"])); ?>
                <!-- important disable attribute for multicheckbox - hidde all checkboxes -->
                <?= $this->formElement($form->get('roles')->setAttributes(['disable'=>true])); ?>
                <?= $this->formElementErrors($form->get('roles')); ?> 
            <?php }?>
               
               
            
                <button type="submit" class="btn-edit-user-form btn-burgundy" data-text="Edit">
                    <span><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</span>
                </button>

            <?= $this->form()->closeTag(); ?>
            
        </div>

        
    </div>
    
</section>

