<?php
$this->headLink()->appendStylesheet('/css/admin.css'); 
$this->headTitle($this->title);

$form->setAttributes(['class'=>'cms']);

$form->get('new_password')->setAttributes(array(
    'class'=>'form-control', 
    ));
$form->get('confirm_new_password')->setAttributes(array(
    'class'=>'form-control',
    ));


$form->get('submit')->setAttributes(['class'=>'btn-about-us btn-burgundy']);

$form->prepare();

?>

<section class="admin">
    
    <div class="header">
        <div class="header-title reverse"><i class="fa fa-key" aria-hidden="true"></i><?= $this->escapeHtml($this->title) ?></div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube4 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-06s"></div>
	</div>
    </div>
    
     <div class='admin-box'>
        
        <div class='form-wrapper'>
            <span>
                <?= $message ?>
            </span>
        </div>
         
        <div class='form-wrapper'>
            
            <?= $this->form()->openTag($form); ?>
            
                <?= $this->formLabel($form->get('new_password')); ?>
                <?= $this->formElement($form->get('new_password')); ?>
                <?= $this->formElementErrors($form->get('new_password')); ?>
            
                <?= $this->formLabel($form->get('confirm_new_password')); ?>
                <?= $this->formElement($form->get('confirm_new_password')); ?>
                <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
            
                <?= $this->formSubmit($form->get('submit')); ?>
            
                <?= $this->formElement($form->get('csrf')); ?>
            
            <?= $this->form()->closeTag(); ?>
        </div>
         
         
         
         
     </div>
    
</section>

