<?php

/*
 *  Schoollife - index
 */
$current_season = $this->layout()->currenSeason->getSeasonName();
$this->headTitle($this->headTitle);

?>

<section class="school-life">
    <div class="header">
	<div class="baner"><img src="img/schoollife/banner.jpg" /></div>
	<div class="header-title"><?= $this->headTitle ?></div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube2 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>						
	</div>
    </div>
					
    <div class="school-life-box">
        <?php  
            if(empty($this->schoolLifeList)){
                echo '<div class="no-content">';
                    
                        echo '<img src="img/icons/icon-gravity-theory.png"/>';
                        echo '<span>There is no "School activity" yet.</span>';
                    
                        
                    
                        
                        
                echo '</div>';
                
//                if ($this->access('classes.add')) {
//                        echo '<div class="cms-option classes">';
//                            echo '<a href="#" class="bs modal-trigger-add-class-blog" data-modal="add-class-blog-modal">';
//                                echo '<img src="img/icons/icon-add.png"><span>Add new class blog</span>';
//                            echo '</a>';
//                        echo '</div>';
//                    }
                
                
                 
            }else{
                echo '<div class="main-col-left">';
                    foreach ($this->schoolLifeList['schoolLife-left'] as $schoolLife) :
                        echo '<div class="main-box">';
                            echo '<div class="title '.$this->schoolLifeList['colors'][$schoolLife->getId()].'">'.$schoolLife->getTitle().'</div>';
                            echo '<ul class="school-life-blog-list">';
                                echo '<li>';
//                                 /*
//                                 * checking only if access to this schoolLife 
//                                 * after verification normal access is implemented in modal show-school-life-modal 
//                                 */
                                   $access = 0;
                                   if ($this->access('schoolLife.manage')){
                                        $access  = 1; 
                                   }
                                    echo '<a href="#" class="modal-trigger-show-school-life" data-modal="show-school-life-modal" data-schoolLifeID="'.$schoolLife->getId().'" data-color="'.$this->schoolLifeList['colors'][$schoolLife->getId()].'" data-access="'.$access.'">';
                                    echo '<span class="roll '.$this->schoolLifeList['colors'][$schoolLife->getId()].'"></span>';
                                    echo '<img src="upload/school-life/'.$schoolLife->getId().'/'.$schoolLife->getPhotoName().'"/>';
                                    echo '</a>';
				echo '</li>';
                            echo '</ul>';
                        echo '</div>';  
                    endforeach;
                    
                echo '</div>';
                
                echo '<div class="main-col-right">';
                    foreach ($this->schoolLifeList['schoolLife-right'] as $schoolLife) :
                        echo '<div class="main-box">';
                            echo '<div class="title '.$this->schoolLifeList['colors'][$schoolLife->getId()].'">'.$schoolLife->getTitle().'</div>';
                            echo '<ul class="school-life-blog-list">';
                                echo '<li>';
//                                 /*
//                                 * checking only if access to this schoolLife 
//                                 * after verification normal access is implemented in modal show-school-life-modal 
//                                 */
                                   $access = 0;
                                   if ($this->access('schoolLife.manage')){
                                        $access  = 1; 
                                   }
                                    echo '<a href="#" class="modal-trigger-show-school-life" data-modal="show-school-life-modal" data-schoolLifeID="'.$schoolLife->getId().'" data-color="'.$this->schoolLifeList['colors'][$schoolLife->getId()].'" data-access="'.$access.'">';
                                    echo '<span class="roll '.$this->schoolLifeList['colors'][$schoolLife->getId()].'"></span>';
                                    echo '<img src="upload/school-life/'.$schoolLife->getId().'/'.$schoolLife->getPhotoName().'"/>';
                                    echo '</a>';
				echo '</li>';
                            echo '</ul>';
                        echo '</div>';
                    endforeach;
                
                echo '</div>';
               
            }
            
        ?>
    </div>	
</section>

<!-- Show School Life Modal -->
<div class="modal" id="show-school-life-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box lg" id="modal-color">
  
    <div class="modal-header">
      	<div class="close-modal">
	      	<div class="close-modal-inner">
                    <label>close</label>
	  	</div>
      	</div>
      	<div class="circle-img-wrapper"><img src="/img/logo_burgundy.png" alt="school" /></div>
      	
      	<!-- original version -->
      	<div class="modal-title" id="showSchoolLifeTitle">
      		<span></span>
      	</div>
      	<!-- end original version -->
      	
    </div>
      
    
 
    <div class="modal-body school-life">
        
        <label class='response-msg'></label>
        <div class="loader"></div>
        
        <div class="admin-option" id="adminOption"></div>
    
		 <div class="modal-text">
		 	<img id="schoolLifeImg" src="">
                        <div id='schoolLifeContent'>
			
                        </div>
		</div>
		<div class="btn-modal-box">
                    <button type="button" class="modal-btn btn-purpure small close-btn" data-text="Close"><span>Close</span></button>
		</div> 
    </div> 
  </div>
</div>
<!-- end Show School Life Modal -->

<!--SCRIPTS-->
<script src="js/blog-hover-effect.js" type="text/javaScript"></script>

<script src="js/school-life-show-info.js" type="text/javaScript"></script>



