<?php

/*
 *  Schoollife - index
 */
$current_season = $this->layout()->currenSeason->getSeasonName();
$this->headTitle($this->headTitle);

?>

<section class="school-life">
    <div class="header">
	<div class="baner"><img src="img/schoollife/banner.jpg" /></div>
	<div class="header-title"><?= $this->title ?></div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube2 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>						
	</div>
    </div>
					
    <div class="school-life-box">
        <?php  
            if(empty($this->schoolLifeList)){
                echo '<div class="no-content">';
                    
                        echo '<img src="img/icons/icon-gravity-theory.png"/>';
                        echo '<span>There is no "School activity" yet.</span>';
                    
                        
                    
                        
                        
                echo '</div>';
                
//                if ($this->access('classes.add')) {
//                        echo '<div class="cms-option classes">';
//                            echo '<a href="#" class="bs modal-trigger-add-class-blog" data-modal="add-class-blog-modal">';
//                                echo '<img src="img/icons/icon-add.png"><span>Add new class blog</span>';
//                            echo '</a>';
//                        echo '</div>';
//                    }
                 
            }else{
                echo '<div class="main-col-left">';
                    foreach ($this->schoolLifeList['left'] as $schoolLife) :
                        echo '<div class="main-box">';
                            echo '<div class="title red">'.$schoolLife->getTitle().'</div>';
                            echo '<ul class="school-life-blog-list">';
                                echo '<li>';	
                                    echo '<a href="#">';
                                    echo '<span class="roll red"></span>';
                                    echo '<img src="upload/school-life/'.$schoolLife->getId().'/'.$schoolLife->getPhotoName().'"/>';
                                    echo '</a>';
				echo '</li>';
                            echo '</ul>';
                        echo '</div>';  
                    endforeach;
                    
                echo '</div>';
                
                echo '<div class="main-col-right">';
                    foreach ($this->schoolLifeList['right'] as $schoolLife) :
                        echo '<div class="main-box">';
                            echo '<div class="title blue">'.$schoolLife->getTitle().'</div>';
                            echo '<ul class="school-life-blog-list">';
                                echo '<li>';	
                                    echo '<a href="#">';
                                    echo '<span class="roll blue"></span>';
                                    echo '<img src="upload/school-life/'.$schoolLife->getId().'/'.$schoolLife->getPhotoName().'"/>';
                                    echo '</a>';
				echo '</li>';
                            echo '</ul>';
                        echo '</div>';
                    endforeach;
                
                echo '</div>';
                
            }
            
        ?>
    </div>	
</section>

<!--SCRIPTS-->
<script src="js/blog-hover-effect.js" type="text/javaScript"></script>



