<?php

/*
 *  Schoollife - index
 */
$current_season = $this->layout()->currenSeason->getSeasonName();
$this->headTitle($this->headTitle);

?>

<section class="school-life">
    <div class="header">
	<div class="baner"><img src="img/schoollife/banner.jpg" /></div>
	<div class="header-title"><?= $this->headTitle ?></div>
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube6 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube2 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>						
	</div>
    </div>
					
    <div class="school-life-box">
        <?php  
            if(empty($this->schoolLifeList)){
                echo '<div class="no-content">';
                    
                        echo '<img src="img/icons/icon-gravity-theory.png"/>';
                        echo '<span>There is no "School activity" yet.</span>';
                    
                        
                    
                        
                        
                echo '</div>';
                
//                if ($this->access('classes.add')) {
//                        echo '<div class="cms-option classes">';
//                            echo '<a href="#" class="bs modal-trigger-add-class-blog" data-modal="add-class-blog-modal">';
//                                echo '<img src="img/icons/icon-add.png"><span>Add new class blog</span>';
//                            echo '</a>';
//                        echo '</div>';
//                    }
                
                
                 
            }else{
                echo '<div class="main-col-left">';
                    foreach ($this->schoolLifeList['schoolLife-left'] as $schoolLife) :
                        echo '<div class="main-box">';
                            echo '<div class="title '.$this->schoolLifeList['colors'][$schoolLife->getId()].'">'.$schoolLife->getTitle().'</div>';
                            echo '<ul class="school-life-blog-list">';
                                echo '<li>';
//                                 /*
//                                 * checking only if access to this schoolLife 
//                                 * after verification normal access is implemented in modal show-school-life-modal 
//                                 */
                                   $access = 0;
                                   if ($this->access('schoolLife.manage')){
                                        $access  = 1; 
                                   }
                                    echo '<a href="#" class="modal-trigger-show-school-life" data-modal="show-school-life-modal" data-schoolLifeID="'.$schoolLife->getId().'" data-color="'.$this->schoolLifeList['colors'][$schoolLife->getId()].'" data-access="'.$access.'">';
                                    echo '<span class="roll '.$this->schoolLifeList['colors'][$schoolLife->getId()].'"></span>';
                                    if($schoolLife->getPhotoName() !== null){
                                        echo '<img src="upload/school-life/'.$schoolLife->getId().'/'.$schoolLife->getPhotoName().'"/>';
                                    }else{
                                        echo '<img src="upload/school-life/dummy.jpg"/>';
                                    }
                                    echo '</a>';
				echo '</li>';
                            echo '</ul>';
                        echo '</div>';  
                    endforeach;
                    
                echo '</div>';
                
                echo '<div class="main-col-right">';
                    foreach ($this->schoolLifeList['schoolLife-right'] as $schoolLife) :
                        echo '<div class="main-box">';
                            echo '<div class="title '.$this->schoolLifeList['colors'][$schoolLife->getId()].'">'.$schoolLife->getTitle().'</div>';
                            echo '<ul class="school-life-blog-list">';
                                echo '<li>';
//                                 /*
//                                 * checking only if access to this schoolLife 
//                                 * after verification normal access is implemented in modal show-school-life-modal 
//                                 */
                                   $access = 0;
                                   if ($this->access('schoolLife.manage')){
                                        $access  = 1; 
                                   }
                                    echo '<a href="#" class="modal-trigger-show-school-life" data-modal="show-school-life-modal" data-schoolLifeID="'.$schoolLife->getId().'" data-color="'.$this->schoolLifeList['colors'][$schoolLife->getId()].'" data-access="'.$access.'">';
                                    echo '<span class="roll '.$this->schoolLifeList['colors'][$schoolLife->getId()].'"></span>';
                                    if($schoolLife->getPhotoName() !== null){
                                        echo '<img src="upload/school-life/'.$schoolLife->getId().'/'.$schoolLife->getPhotoName().'"/>';
                                    }else{
                                        echo '<img src="upload/school-life/dummy.jpg"/>';
                                    }
                                    echo '</a>';
				echo '</li>';
                            echo '</ul>';
                        echo '</div>';
                    endforeach;
                
                echo '</div>';
               
            }
            
        ?>
    </div>	
</section>

<!-- Show School Life Modal -->
<div class="modal" id="show-school-life-modal">
  <div class="modal-sandbox"></div>
  <div class="modal-box lg" id="modal-color">
  
    <div class="modal-header">
      	<div class="close-modal">
	      	<div class="close-modal-inner">
                    <label>close</label>
	  	</div>
      	</div>
      	<div class="circle-img-wrapper"><img src="/img/logo_burgundy.png" alt="school" /></div>
      	
      	<!-- original version -->
      	<div class="modal-title" id="showSchoolLifeTitle">
      		<span></span>
      	</div>
      	<!-- end original version -->
      	
    </div>
      
    
 
    <div class="modal-body school-life">
        
        <label class='response-msg'></label>
        <div class="loader"></div>
        
        <div class="admin-option" id="adminOption">
            <a href="#" class="tooltip modal-trigger-edit-school-life" data-modal="edit-school-life-modal">
                <button class="btn-admin"><img src="img/icons/icon-edit-blue.png"></button>
                <span class="tooltiptext bottom edit">Edit</span>
            </a>
            <a href="#" class="tooltip modal-trigger-delete-school-life" data-modal="delete-school-life-modal">
                <button class="btn-admin"><img class="icon-list" src="img/icons/icon-bin-red.png"></button>
                <span class="tooltiptext bottom remove">Remove</span>
            </a>
        </div>
    
		 <div class="modal-text">
		 	<img id="schoolLifeImg" src="">
                        <div id='schoolLifeContent'>
			
                        </div>
		</div>
		<div class="btn-modal-box">
                    <button type="button" class="modal-btn btn-purpure small close-btn" data-text="Close"><span>Close</span></button>
		</div> 
    </div> 
  </div>
</div>
<!-- end Show School Life Modal -->

<!-- Edit School Life Modal-->
<div class="modal" id="edit-school-life-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="policy-icon-edit" src="img/icons/icon-edit.png" alt="" /></div>

            
            <!-- original version -->
            <div class="modal-title">
                    <span>Edit School Life</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="editSchoolLifeForm" class="cms" enctype="multipart/form-data"> 
                    
                    <input type="hidden" id="editSchoolLifeID" name="editSchoolLifeID" required/>
                    
                    <div class="width-60-left">
                        <label for="editSchoolLifeTitle">Edit title:</label>
                        <input type="text" id="editSchoolLifeTitle" name="editSchoolLifeTitle"  autocomplete="off">
                    </div>
                    <div class="width-35-right">
                        <label for="editSchoolLifeStatus">Status:</label>
                        <select id="editSchoolLifeStatus" name="editSchoolLifeStatus" class="dropdown"></select>                  
                    </div>
                    
                    <div class='width-60-left'>
                        <label for="editSchoolLifeContent">Edit content (text):</label>
                        <textarea id="editSchoolLifeContent" name="editSchoolLifeContent" rows="10"></textarea>
                    </div>
                    
                    <div class='width-35-right'>                       
                        <div class="width-100">
                            <label id='editSchoolLifePhotoLabel_current'>Current photo:</label>
                            <label id='editSchoolLifePhotoLabel'>Add photo:</label>
                            <label class='preview-img-label edit-school-life' id='preview-photo-edit-school-life-label'><a href='#'>X</a></label>
                            <img class='preview-img edit-school-life' id='editSchoolLifePhoto_current' />


                            <input type="file" id="editSchoolLifePhoto" name="editSchoolLifePhoto">
                            <input type="checkbox" class='to_remove' id='edit-school-life-remove-photo'>
                        </div>
                    </div>

                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Save"><span>Save</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Cancel"><span>Cancel</span></button>
                    </div>
		</form>          
     
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Edit School Life Modal-->

<!-- Delete School Life -->
<div class="modal" id="delete-school-life-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-bin.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove School Life</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-school-life'>You really want to delete <span></span></div>
                <form id="deleteSchoolLifeForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deleteSchoolLifeID" name="deleteSchoolLifeID" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end School Life Modal -->

<!--SCRIPTS-->
<script src="js/blog-hover-effect.js" type="text/javaScript"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>
<script src="js/summernote/summernote-options.js" type="text/javaScript"></script>

<script src="js/school-life-show-info.js" type="text/javaScript"></script>
<script src="js/school-life-edit.js" type="text/javaScript"></script>
<script src="js/school-life-delete.js" type="text/javaScript"></script>



