<?php

/*
 *  Main - index
 */
$current_season = $this->layout()->currenSeason->getSeasonName();
$aboutUs = $this->layout()->aboutUs;

?>
<!-- SECTION SLIDER -->
<section class="banner">
    <!-- SLIDER -->
    <div class="slider">
	<div><img src="img/slider/banner-1.jpg"></div>
	<div><img src="img/slider/banner-2.png"></div>
	<div><img src="img/slider/banner-3.png"></div>
        <div><img src="img/slider/banner-4.png"></div>
	<div><img src="img/slider/banner-5.png"></div>
	<div><img src="img/slider/banner-6.png"></div>
        <div><img src="img/slider/banner-7.png"></div>
        <div><img src="img/slider/banner-8.png"></div>
        <div><img src="img/slider/banner-9.png"></div>
        <div><img src="img/slider/banner-10.png"></div>
    </div>
    <!-- WELCOME TEXT -->
    <div class="welcome-msg">
        <?php if ($this->access('welcomemsg.edit')) {
            echo '<div class="cms-option">'
                .'<a href="#" class="bs modal-trigger-welcome-msg-edit" data-modal="edit-welcome-msg-modal" data-id="'.$welcomeMsg->getId().'">'
                    .'<img src="img/icons/icon-edit.png">'
                    .'<span>Edit</span>'
                .'</a>';
            echo '</div>';
        } ?>
        
	<div class="welcome-title">Welcome</div>	
	<div class="color-cubes">
            <div class="single-cube1 wow fadeInRightBig delay-01s"></div>
            <div class="single-cube2 wow fadeInRightBig delay-02s"></div>
            <div class="single-cube3 wow fadeInRightBig delay-03s"></div>
            <div class="single-cube4 wow fadeInRightBig delay-04s"></div>
            <div class="single-cube5 wow fadeInRightBig delay-05s"></div>
	</div>
	<div class="text">
            <?= $welcomeMsg->getContent() ?>
	</div>
	<div class="about-box">
            <button type="button" class="modal-trigger btn-about-us btn-burgundy" data-modal="about-us" data-text="About us">
		<span><i class="fa fa-graduation-cap faa-tada animated"></i> About us</span>
            </button>
	</div>
    </div>
</section>

<!-- SCHOOL BOX -->
<section class="main-page">

    <?php
        // module/Album/view/album/album/index.phtml:
        $left_right_adjust = 2;
    ?>
    
    <!-- NEWS BOX -->
    <div class="main-col-left"> 
        <div class="news-box">
            <?php if ($this->access('news.add')) {
                echo '<div class="cms-option news">'
                        . '<a href="#" class="bs modal-trigger-add-news" data-modal="add-news-modal" data-authorID="'.$this->currentUser()->getId().'" data-blogID="'.$this->blog->getId().'">'
                            . '<img src="img/icons/icon-add.png"><span>Add news</span>'
                        . '</a>'
                    . '</div>';
            } ?>

            <div class="title blue">School news</div>
            <?php
                if($this->paginator->getTotalItemCount() == 0){
                    echo '<div class="school-news">';
                        echo '<div class="no-content">';
                            echo '<img src="img/icons/icon-summer.png"/>';
                            echo '<span>Summer break<br>New news for the '.$current_season.'<br>comming soon ... </span>';
                        echo '</div>';
                    echo '</div>';
                }else{
                    foreach($this->paginator  as $news){
                        $type = null;
                        $reflect = new ReflectionClass($news);
                            if($reflect->getShortName() === 'NewsPost'){
                                $type = 'news';
                            }
                            if($reflect->getShortName() === 'GalleryPost'){
                                $type = 'gallery';
                            } 
                            if($reflect->getShortName() === 'ClassPost'){
                                $type = 'classes';
                            }
                        if($type === 'news'){
                            echo '<div class="school-news">';
                                if($this->escapeHtml($news->getPhotoName()) !==null){
                                    if($left_right_adjust % 2){
                                        echo '<img class="left" src="upload/school-news/'.$this->blog->getSeason()->getSeasonName().'/'.$this->escapeHtml($news->getId()).'/'.$this->escapeHtml($news->getPhotoName()).'">';
                                    }else{
                                        echo '<img class="right" src="upload/school-news/'.$this->blog->getSeason()->getSeasonName().'/'.$this->escapeHtml($news->getId()).'/'.$this->escapeHtml($news->getPhotoName()).'">';
                                    }
                                    $left_right_adjust++;
                                }
                                echo '<div class="news-title">'.$this->escapeHtml($news->getTitle()).' - News</div>';
                                echo '<hr class="blue">';
                                echo '<div class="news-date"><img src="img/icons/icon-calendar.png">'.date('d F Y',strtotime($news->getDatePublished())) .'</div>';
                                echo '<p>'.$this->escapeHtml($news->getContent()).'</p>';
                                if($news->getDocName() != null) {                                                                     
                                    echo '<div class="news-link">';                                          
                                            echo '<img src="img/icons/icon-download.png">';
                                            echo '<a target="_blank" class="bs blue" href="upload/school-news/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getId().'/doc/'.$news->getDocName().'">';
                                                echo '<span class="">see attachment</span>';
                                            echo '</a>';     
                                    echo '</div>';
                                }
                                echo '<div class="news-admin">';
                                    if ($this->access('news.edit')) {
                                        echo '<a href="#" class="tooltip modal-trigger-edit-news" data-modal="edit-news-modal" data-id="'. $this->escapeHtml($news->getId()).'">'
                                            .'<button class="btn-admin">'
                                                .'<img src="img/icons/icon-edit-blue.png" >'
                                            .'</button>'
                                            .'<span class="tooltiptext bottom edit">Edit</span>';
                                        echo '</a>';
                                    }
                                    if ($this->access('news.delete')) {
                                        echo '<a href="#" class="tooltip modal-trigger-delete-news" data-modal="delete-news-modal" data-id="'.$this->escapeHtml($news->getId()).'" data-title="'.$this->escapeHtml($news->getTitle()).'">'
                                                .'<button class="btn-admin">'
                                                    .'<img class="icon-list" src="img/icons/icon-bin-red.png" >'
                                                .'</button>'
                                            .'<span class="tooltiptext bottom remove">Remove</span>';
                                        echo '</a>';
                                    }
                                echo '</div>';
                            echo '</div>'; 
                            
                        }
                        if($type === 'gallery' || $type === 'classes'){
                            $photoGallery = $news->getPostGallery();
                            echo '<div class="school-news">';
                                if(sizeof($photoGallery) > 0){
                                    $countPhoto = 1;                // first photo from post gallery
                                    foreach($photoGallery as $photo){
                                        if($countPhoto === 1){
                                            if($left_right_adjust % 2){
                                                echo '<a class="lightbox" href="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/'.$photo->getPhotoName().'">';
                                                    echo '<img class="left" src="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/'.$photo->getPhotoName().'" alt="">';
                                                echo '</a>';
                                            }else{
                                                echo '<a class="lightbox" href="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/'.$photo->getPhotoName().'">';
                                                    echo '<img class="right" src="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/'.$photo->getPhotoName().'" alt="">';
                                                echo '</a>';
                                            }
                                            $left_right_adjust++;
                                        }else{
                                            echo '<div class="hidden">';
                                                echo '<a class="lightbox" href="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/'.$photo->getPhotoName().'">';
                                                    echo '<img src="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/'.$photo->getPhotoName().'" alt="">';
                                                echo '</a>';
                                            echo '</div>';
                                        }
                                        $countPhoto ++;
                                    }
                                    
                                }else{
                                    if($type === 'gallery' || ($type === 'classes' && $news->getVideoName() !== null)){
                                        if($left_right_adjust % 2){
                                            echo '<video controls class="left">';
                                                echo '<source src="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/video/'.$news->getVideoName().'" type="video/mp4">';                                        
                                            echo '</video>';
                                        }else{
                                            echo '<video controls class="right">';
                                                echo '<source src="upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/video/'.$news->getVideoName().'" type="video/mp4">';                                        
                                            echo '</video>';
                                        }
                                        $left_right_adjust++;
                                    }
                                    
                                }
                                if($type === 'gallery'){
                                    echo '<div class="news-title">'.$this->escapeHtml($news->getTitle()).' - Gallery</div>';
                                }
                                if($type === 'classes'){
                                    echo '<div class="news-title">'.$this->escapeHtml($news->getTitle()).' - Class Blog</div>';
                                }
                                echo '<hr class="blue">';
                                echo '<div class="news-date"><img src="img/icons/icon-calendar.png">'.date('d F Y',strtotime($news->getDatePublished())) .'</div>';
                                
                                echo '<p>'.$this->escapeHtml($news->getContent()).'</p>';
                                
                                if($news->getVideoName() !== null && sizeof($photoGallery) > 0){
                                        echo '<div class="news-link">';                                          
                                            echo '<img src="img/icons/icon-video.png">';
                                            $video_link = 'upload/'.$type.'/'.$this->blog->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/video/'.$news->getVideoName();
                                            echo '<a class="bs blue modal-trigger-show-video" data-modal="show-video-modal" data-video="'.$video_link.'" data-title="'.$news->getTitle().'">';
                                                echo '<span class="">see also video</span>';
                                            echo '</a>';     
                                        echo '</div>';
                                }
                                if($type === 'classes'){
                                    if($news->getDocName() != null) {                                                                     
                                        echo '<div class="news-link">';                                          
                                                echo '<img src="img/icons/icon-download.png">';
                                                echo '<a target="_blank" class="bs blue" href="upload/'.$type.'/'.$news->getSeason()->getSeasonName().'/'.$news->getBlog()->getId().'/'.$news->getId().'/doc/'.$news->getDocName().'">';
                                                    echo '<span class="">see attachment</span>';
                                                echo '</a>';     
                                        echo '</div>';
                                    }
                                }
                                echo '<div class="news-admin">';
                                    if($type === 'gallery'){
                                        if ($this->access('gallery.edit')) {
                                            echo '<a href="#" class="tooltip modal-trigger-edit-gallery" data-modal="edit-gallery-modal" data-authorID="'.$this->currentUser()->getId().'" data-galleryID="'.$news->getId().'">'
                                                .'<button class="btn-admin">'
                                                    .'<img src="img/icons/icon-edit-blue.png" >'
                                                .'</button>'
                                                .'<span class="tooltiptext bottom edit">Edit</span>';
                                            echo '</a>';
                                        }
                                        if ($this->access('gallery.delete')) {
                                            echo '<a href="#" class="tooltip modal-trigger-delete-gallery" data-modal="delete-gallery-modal" data-galleryID="'.$news->getId().'" data-galleryTitle="'.$news->getTitle().'">'
                                                    .'<button class="btn-admin">'
                                                        .'<img class="icon-list" src="img/icons/icon-bin-red.png" >'
                                                    .'</button>'
                                                .'<span class="tooltiptext bottom remove">Remove</span>';
                                            echo '</a>';
                                        }
                                    }
                                    if($type === 'classes'){
                                        /*
                                        * EDIT POST (left col)
                                        */
                                         if($news->getBlog()->getLearningSupport() !== null){
                                            if ($this->access('post.edit') ||
                                                 $this->access('post.own.edit', ['user'=>$news->getBlog()->getTeacher()]) ||
                                                 $this->access('post.own.edit', ['user'=>$news->getBlog()->getLearningSupport()])) {

                                                 echo '<a href="#" class="tooltip modal-trigger-edit-post" data-modal="edit-post-modal" data-postID="'.$news->getId().'" data-authorID="'.$this->currentUser()->getId().'" data-teacherID="'.$news->getBlog()->getTeacher()->getId().'" data-learningSupportID="'.$news->getBlog()->getLearningSupport()->getId().'">'
                                                         .'<button class="btn-admin">'
                                                             .'<img src="img/icons/icon-edit-blue.png" >'
                                                         .'</button>'
                                                         .'<span class="tooltiptext bottom edit">Edit</span>'
                                                     . '</a>';

                                            }
                                         }else{ ;
                                            //no learning support
                                            $learningSupportID = null;
                                            if ($this->access('post.edit') ||
                                                $this->access('post.own.edit', ['user'=>$news->getBlog()->getTeacher()])) {

                                                echo '<a href="#" class="tooltip modal-trigger-edit-post" data-modal="edit-post-modal" data-postID="'.$news->getId().'" data-authorID="'.$this->currentUser()->getId().'" data-teacherID="'.$news->getBlog()->getTeacher()->getId().'" data-learningSupportID="'.$learningSupportID.'">'
                                                        .'<button class="btn-admin">'
                                                            .'<img src="img/icons/icon-edit-blue.png" >'
                                                        .'</button>'
                                                        .'<span class="tooltiptext bottom edit">Edit</span>'
                                                    . '</a>';

                                            }
                                        }
                                    /*
                                    * DELETE POST (left col)
                                    */
                                    if($news->getBlog()->getLearningSupport() !== null){
                                        if ($this->access('post.delete') ||
                                                $this->access('post.own.delete', ['user'=>$news->getBlog()->getTeacher()]) ||
                                                $this->access('post.own.delete', ['user'=>$news->getBlog()->getLearningSupport()])) {

                                            echo '<a href="#" class="tooltip modal-trigger-delete-post" data-modal="delete-post-modal" data-postID="'.$news->getId().'" data-postTitle="'.$news->getTitle().'" data-teacherID="'.$news->getBlog()->getTeacher()->getId().'" data-learningSupportID="'.$news->getBlog()->getLearningSupport()->getId().'">'
                                                    .'<button class="btn-admin">'
                                                        .'<img class="icon-list" src="img/icons/icon-bin-red.png" >'
                                                    .'</button>'
                                                    .'<span class="tooltiptext bottom remove">Remove</span>'
                                                . '</a>';      
                                        }
                                    }else{
                                        //no learning support
                                        $learningSupportID = null;
                                        if ($this->access('post.delete') ||
                                                $this->access('post.own.delete', ['user'=>$news->getBlog()->getTeacher()])) {
                                            
                                            echo '<a href="#" class="tooltip modal-trigger-delete-post" data-modal="delete-post-modal" data-postID="'.$news->getId().'" data-postTitle="'.$news->getTitle().'" data-teacherID="'.$news->getBlog()->getTeacher()->getId().'" data-learningSupportID="'.$learningSupportID.'">'
                                                    .'<button class="btn-admin">'
                                                        .'<img class="icon-list" src="img/icons/icon-bin-red.png" >'
                                                    .'</button>'
                                                    .'<span class="tooltiptext bottom remove">Remove</span>'
                                                . '</a>';
                                            
                                        }
                                    }
                                        
                                    }
                                echo '</div>';
                            echo '</div>'; 
                        }
                    }
                }
            ?>



            <?= $this->paginationControl(
                // The paginator object:
                $this->paginator,
                // The scrolling style:
                'sliding',
                // The partial to use to render the control:
                'partial/paginator',
                // The route to link to when a user clicks a control link:
                ['route' => 'application', 'action' => 'index']
            ) ?>

        </div>
    </div>
    
    
    <!-- end NEWS BOX -->
    <div class="main-col-right">
        <!-- EVENT-BOX -->
        <div class="event-box">
            <?php if ($this->access('event.add')) {
                echo '<div class="cms-option events">'
                    .'<a href="#" class="bs modal-trigger-add-event" data-modal="add-event-modal" data-authorID="'.$this->currentUser()->getId().'">'
                        .'<img src="img/icons/icon-add.png">'
                        .'<span>Add event</span>'
                    .'</a>';
                echo '</div>';
            } ?>

            <div class="title orange">Events</div>

            <div id="calendar_div">

                <div id="calendar-page" >
                    <div id='current_date' class="current_date"></div>
                    <hr class="orange">
                    <div id="event_list"></div>
                </div>          
                <div id="calender_section">

                </div>
            </div>
            
            <?php
                if(!empty($this->schoolEvents)){
                    echo '<div class="event-footer">';
                        echo'<a href="#" class="bs orange modal-trigger" data-modal="events-list">';
                            echo'<img src="img/icons/icon-event2.png">';
                            echo'<span class="see-all">see all events</span>';
                        echo'</a>';
                    echo'</div>';
                }
            ?>
        </div>
        <!-- end EVENT-BOX -->
        
        
        <!-- NEWSLETTER-BOX -->
        <div class="newsletter-box">
            <?php if ($this->access('newsletter.add')) {
                echo '<div class="cms-option newsletter">'
                    .'<a href="#" class="bs modal-trigger" data-modal="manage-newsletter-modal">'
                        .'<img src="img/icons/icon-settings.png">'
                        .'<span>Manage newsletters</span>'
                    .'</a>';
                echo '</div>';
            } ?>

            <div class="title purpure"><span>Newsletter</span></div>
            <hr class="purpure">
            <div class="newsletters-list">
                <?php 
                
                if(!empty($this->newsletters)){                 
                        
                    echo '<div class="newsletter-latest-month">';
                        echo '<div class="newsletter-title">'.$this->newsletters[1]['month'].'</div>';
                        foreach ($this->newsletters[1]['newsletters']  as $newsletter) :
                            
                            echo '<div class="list-element">';
                                echo '<img class="icon-list" src="img/icons/icon-download.png">';
                                    echo '<a target="_blank" class="bs purpure" href="upload/newsletters/'.$current_season.'/'.$this->escapeHtml($newsletter->getDocName()).'">';
                                        echo '<span class="">'.$newsletter->getTitle().' '.date('jS F Y',strtotime($newsletter->getDateNewsletter())).'</span>';
                                    echo '</a>';
                            echo '</div>';
                                
                        endforeach;
                        
                    echo '</div>';
                    
                    
                        if(array_key_exists(2, $this->newsletters)){
                            echo '<div class="newsletter-month-before">';
                                echo '<div class="newsletter-title">'.$this->newsletters[2]['month'].'</div>';
                                foreach ($this->newsletters[2]['newsletters']  as $newsletter) :

                                    echo '<div class="list-element">';
                                        echo '<img class="icon-list" src="img/icons/icon-download.png">';
                                        echo '<a target="_blank" class="bs purpure" href="upload/newsletters/'.$current_season.'/'.$this->escapeHtml($newsletter->getDocName()).'">';
                                            echo '<span class="">'.$newsletter->getTitle().' '.date('jS F Y',strtotime($newsletter->getDateNewsletter())).'</span>';
                                        echo '</a>';
                                    echo '</div>';

                                endforeach;
                            echo '</div>';
                        }else{
                            echo '<div class="newsletter-month-before empty">';
                                echo '<div class="no-content">';
                                    echo '<img src="img/icons/icon-kite.png"/>';
                                echo '</div>';
                            echo '</div>';
                        }

                    
                    if(sizeof($this->newsletters) > 2 ){
                        echo '<div class="more-newsletter">	';							
                            echo '<a href="#" class="bs purpure modal-trigger" data-modal="older-newsletter"> ';
                                echo '<img src="img/icons/icon-archive.png"> ';
                                echo '<span class="older">see older</span>';
                            echo '</a>';
                        echo '</div>';
                    }
                }else{
                    echo '<div class="no-content">'
                                .'<img src="img/icons/icon-kite.png"/>'
                                .'<span>There is no newsletters yet ...</span>';
                    echo '</div>';
                }
                ?>
                
                
            </div>

<!--            <div class="subscribe">
                <div class="sub-start">
                    <div class="sub-logo">
                        <img src="img/icons/icon-envelope-purpure.png">
                    </div>
                    <h2 class="sub-heading">signup with your email to get latest updates</h2>

                    <form id="subscribeForm">
                        <input id="sub-email" name='email' placeholder="enter your email" >
                        <button id="subscribe-btn" type="submit" class="btn-subscribe btn-purpure" data-text="subscribe">
                            <span><i class="fa fa-bell faa-tada animated"></i> subscribe</span>
                        </button>
                    </form>
                </div>
                <div class="sub-end">
                    <h3></h3>
                    <div class="close-subscribing"></div>
                </div>
            </div>					-->
        </div>
        <!-- end NEWSLETTER-BOX -->

        <!-- OUR AWARDS -->
        <div class="our-awards-box">
            <?php if ($this->access('award.add')) {
                echo '<div class="cms-option our-awards">';
                    echo '<a href="#" class="bs modal-trigger" data-modal="manage-our-awards-modal">';
                        echo '<img src="img/icons/icon-settings.png"><span>Manage awards</span>';
                    echo '</a>';
                echo '</div>';
            } ?>
            <div class="title red">Our Awards</div>
            <hr class="red">
            <?php 

            foreach ($this->ourAwards  as $award) :

                echo '<div class="award-wrapper">';
                        echo '<span class="helper"></span>'
                        . '<img src="upload/awards/'.$award->getPhotoName().'" alt="'.$award->getTitle().'">'
                    . '</div>';



            endforeach;?>

        </div>
    
    </div>
    
    <!-- end OUR AWARDS -->
</section>

<!--*********************************
*********************************
*********************************
 MODALS 
*********************************
*********************************
*********************************-->
<!-- Add News Modal-->
<div class="modal" id="add-news-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="news" src="img/icons/icon-news.png" alt="" /></div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Add news</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="addNewsForm" class="cms" enctype="multipart/form-data"> 
                    <div class="width-60-left">
                        <label for="addNewsTitle">News title:</label>
                        <input type="text" id="addNewsTitle" name="addNewsTitle" required>
                    </div>
                    
                    <div class="width-35-right">
                        <label id="addNewsDocLabel_current">Current document:</label>
                        <label id="addNewsDocLabel">Add document:</label>
                        <label class='input-X-button' id='preview-doc-add-news-label' for="preview-doc-add-news"><a href='#'>X</a></label>
                        <input type="file" id="addNewsDoc" name="addNewsDoc">
                    </div>
                    
                    <div class='width-60-left'>
                        <label for="addNewsContent">News text:</label>
                        <textarea id="addNewsContent" name="addNewsContent" rows="10"></textarea>
                    </div>
                    
                    <div class='width-35-right'>                       
                        <div class="width-100">
                            <label id="addNewsPhotoLabel_current">Current news photo:</label>
                            <label id="addNewsPhotoLabel">Add news photo:</label>
                            

                            <label class='preview-img-label add-news' id='preview-img-add-news-label' for="preview-img-add-news"><a href='#'>X</a></label>
                            <img class='preview-img add-news' id='preview-img-add-news'>

                            <input type="file" id="addNewsPhoto" name="addNewsPhoto">
                        </div>
                    </div>
                    
                    <input type="hidden" id="addNewsAuthorID" name="addNewsAuthorID" required>
                    <input type="hidden" id="addNewsBlogID" name="addNewsBlogID" required>

                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Add news"><span>Add news</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Add News Modal-->

<!-- Edit News Modal-->
<div class="modal" id="edit-news-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="news-edit" src="img/icons/icon-edit.png" alt="" /></div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Edit news</span>
            </div>
	
        </div>
        <div class="modal-body">
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="editNewsForm" class="cms" enctype="multipart/form-data">
                    <input id="editNewsID" name='editNewsID' type="hidden">
                    
                    <div class="width-60-left">
                        <label for="editNewsTitle">News title</label>
                        <input type="text" id="editNewsTitle" name="editNewsTitle" required>
                    </div>
                    
                    <div class='width-35-right'>
                        <label id='editNewsDocLabel_current'>Current document:</label>
                        <label id='editNewsDocLabel'>Add document:</label>
                        <table id='editNewsDoc_current'>
                            <tr>
                                <td class="icon"><img class="icon" src="img/icons/icon-document.png"></td>
                                <td class="text" id='editNewsDocTitle'></td>
                                <td class="option">
                                    <label class="preview-doc-label" id="preview-doc-edit-news-label_current">
                                        <a href="#" class="remove_field_doc">X</a>
                                    </label>
                                </td>
                            </tr>
                        </table>
                        
                        <label class='input-X-button' id='preview-doc-edit-news-label'><a href='#'>X</a></label>
                        <input type="file" id="editNewsDoc" name="editNewsDoc">
                        <input type="checkbox" class='to_remove' id='edit-news-remove-doc'>
                    </div>
                    
                    <div class='width-60-left'>
                        <label for="editNewsContent">News text:</label>
                        <textarea id="editNewsContent" name="editNewsContent" rows="10"></textarea>
                    </div>
                    
                    
                    <div class='width-35-right'>
                        <label id='editNewsPhotoLabel_current'>Current photo:</label>
                        <label id='editNewsPhotoLabel'>Add news photo:</label>
                        <label class='preview-img-label edit-news' id='preview-photo-edit-news-label'><a href='#'>X</a></label>
                        <img class='preview-img edit-news' id='editNewsPhoto_current' />
                        
                        
                        <input type="file" id="editNewsPhoto" name="editNewsPhoto">
                        <input type="checkbox" class='to_remove' id='edit-news-remove-photo'>
                    </div>
                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Save"><span>Save</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Cancel"><span>Cancel</span></button>
                    </div>
		</form>
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Edit News Modal-->

<!-- Delete News Modal -->
<div class="modal" id="delete-news-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper">
            <?php 
                echo '<img class="events" src="'.$this->basePath() .'/img/icons/icon-bin.png" alt="" />';
            ?>           
        </div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove News</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-news'>You really want to delete the news: <span></span></div>
                <form id="deleteNewsForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deleteNewsID" name="deleteNewsID" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end delete news Modal -->

<!-- Edit Welcome message Modal-->
<div class="modal" id="edit-welcome-msg-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img src="img/icons/icon-edit.png" alt="" /></div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Edit welcome message</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                <form id="editWelcomeMsgForm" class="cms">
                    <input id="editWelcomeMsgID" name='editWelcomeMsgID' type="hidden">
                    
                    <label for="editWelcomeMsgContent">Welcome message (text):</label>
                    <textarea id="editWelcomeMsgContent" name="editWelcomeMsgContent" rows="10"></textarea>
                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Save"><span>Save</span></button>
                        <button type="button" class="modal-btn btn-red small close-btn right" data-text="Cancel"><span>Cancel</span></button>
                    </div>
		</form>
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Edit Welcome message Modal-->

<!-- About-us Modal -->
<div class="modal" id="about-us">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
  
    <div class="modal-header photo">
      	<div class="close-modal">
            <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img src="img/logo_burgundy.png" alt="school" /></div>
      	
      	<!-- original version -->
      	<!-- <div class="modal-title">
      		<span>About us</span>
      	</div> -->
      	
      	<!-- img version -->
    	<img class="bg-img" src="img/about-us/about-us.jpg"/>
      	<div class="cut-box">	
            <div class="modal-title">
      		<span>About us</span>
            </div>
            <div class="modal-title-cut"></div>
    	</div>
    	<!-- end img version -->	
    </div>
 
    <div class="modal-body">
        <?php if ($this->access('aboutus.edit')) {
            echo '<div class="cms-option about-us">'
                .'<a href="#" class="bs modal-trigger-about-us-edit" data-modal="about-us-edit-modal" data-id="'.$aboutUs->getId().'">'
                    .'<img src="img/icons/icon-edit.png">'
                    .'<span>Edit</span>'
                .'</a>';
            echo '</div>';
        } ?>
	<div class="modal-text">
            <div id="content-lg-text">
            <h1><span id="title"><?= $aboutUs->getTitle() ?></span></h1>
            <hr class="burgundy">
                <?= $aboutUs->getContent() ?>
            <h3><span id="principal_greetings">Le gach dea-ghu&iacute;,</span></h3>
            <h3><span id="principal_name"><?= $aboutUs->getPrincipalName() ?></span></h3>
            </div>
			
	</div>
	<div class="btn-modal-box">
            <button type="button" class="modal-btn btn-burgundy small close-btn" data-text="Close"><span>Close</span></button>
	</div>
    </div> 
        
  </div>
</div>
<!-- end About-us Modal -->


<!-- About-us Edit Modal -->
<div class="modal" id="about-us-edit-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img src="img/logo_burgundy.png" alt="school" /></div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Edit About us</span>
            </div>
	
        </div>
        <div class="modal-body">
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="editAboutUsForm" class="cms"> 
                    <input id="editAboutUsID" name='editAboutUsID' type="hidden">
                    <div class="width-100">
                        <label for="editAboutUsTitle">Title:</label>
                        <input id="editAboutUsTitle" name="editAboutUsTitle" type="text">
                    </div>
                    <div class="width-100">
                        <label for="editAboutUsContent">About us (text):</label>
                        <textarea id="editAboutUsContent" name="editAboutUsContent" rows="10"></textarea>
                    </div>
                    <div class="width-100">
                        <label for="editAboutUsPrincipalName">Principal name:</label>
                        <input id="editAboutUsPrincipalName" name="editAboutUsPrincipalName" type="text">
                    </div>
                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Save"><span>Save</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Cancel"><span>Cancel</span></button>
                    </div>
                    
		</form>
              
            </div>
            
        </div>
    </div>
</div>
<!-- end About-us Edit Modal -->

<!-- Older Newsletters Modal -->
<div class="modal" id="older-newsletter">
<!--  <div class="modal-sandbox"></div>-->
  <div class="modal-box sm purpure">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-archive-purpure.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Older Newsletters</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <hr class="purpure" />
            
               
                <?php                    
                    $count_nl = 1 ;                   
                    foreach($this->newsletters as $newslettersMonth){
                        if($count_nl > 2){
                            $monthName = $newslettersMonth['month'];
                            
                            echo '<div class="newsletter-title">'.$monthName.'</div>';
                            
                            $newsletters = $newslettersMonth['newsletters'];
                            
                            foreach($newsletters as $newsletter){
                                
                                echo '<div class="small-table no-border">';
                                    echo '<div class="small-table-row ">';
                                        echo '<div class="small-table-cell icon-cell">';
                                            echo '<img class="newsletter-download" src="img/icons/icon-download.png" >';
                                        echo '</div>';
                                        echo '<div class="small-table-cell long-title">';
                                            echo '<a target="_blank" class="bs purpure" href="upload/newsletters/'.$current_season.'/'.$this->escapeHtml($newsletter->getDocName()).'">';
                                                echo '<span>'.$newsletter->getTitle().' '.date('jS F Y',strtotime($newsletter->getDateNewsletter())).'</span>';                                          
                                            echo '</a>';
                                        echo '</div>';

                                    echo '</div>';
                                echo '</div>';
                            }
                        }
                            
                        $count_nl++;
                    }

                ?>

            
            <hr class="purpure" />
    
            <div class="btn-modal-box">
                <button type="button" class="modal-btn btn-purpure small close-btn" data-text="Close"><span>Close</span></button>
            </div> 
	</div>
	
    </div> 
  </div>
</div>
<!-- end Older Newsletters Modal -->

<!-- Manage Newsletter Modal -->
<div class="modal" id="manage-newsletter-modal">
<!--  <div class="modal-sandbox"></div>-->
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Manage Newsletters</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-newsletter btn-max btn-purpure reversed" data-modal="add-newsletter-modal" data-text="Add newsletter">
                    <span><i class="fa fa-plus"></i>Add newsletter</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
<!--            <div class="table-header">List of newletters</div>-->
           
            <?php 
                foreach($this->newsletters as $newslettersMonth){
                       
                    $monthName = $newslettersMonth['month'];
                            
                    echo '<div class="newsletter-title">'.$monthName.'</div>';
                            
                    $newsletters = $newslettersMonth['newsletters'];
                            
                    foreach($newsletters as $newsletter){
                                
                        echo '<div class="small-table no-border">';
                            echo '<div class="small-table-row ">';
                                echo '<div class="small-table-cell icon-cell">';
                                    echo '<img class="newsletter-download" src="img/icons/icon-download.png" >';
                                echo '</div>';
                                echo '<div class="small-table-cell long-title">';
                                    echo '<a target="_blank" class="bs purpure" href="upload/newsletters/'.$current_season.'/'.$this->escapeHtml($newsletter->getDocName()).'">';
                                        echo '<span>'.$newsletter->getTitle().' '.date('jS F Y',strtotime($newsletter->getDateNewsletter())).'</span>';                                          
                                    echo '</a>';
                                echo '</div>';

                                echo '<div class="small-table-cell remove">';
                                    if ($this->access('newsletter.delete')) {
                                        echo '<a href="#" class="modal-trigger-delete-newsletter tooltip" data-modal="delete-newsletter-modal" data-id="'.$newsletter->getId().'" data-title="'.$newsletter->getTitle().'" data-date="'.date('jS F Y',strtotime($newsletter->getDateNewsletter())).'">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-bin-red.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext remove">Remove</span>';
                                        echo '</a>';
                                    }                               
                                echo '</div>';

                            echo '</div>';
                        echo '</div>';
                    }
                        
                }

            ?>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Manage Newsletter Modal -->

<!-- Add Newsletters Modal -->
<div class="modal" id="add-newsletter-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-envelope-burgundy.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Add Newsletters</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <form id="addNewsletterForm" class="cms" enctype="multipart/form-data">
                    
<!--                    <div class='width-100'>
                        <label id="newsletterTitle-label" for="addNewsletterTitle">Newsletter title</label>
                        <input type="text" id="addNewsletterTitle" name="addNewsletterTitle" required>
                    </div>-->
                    
                    <div class='width-100'>
                        <label for="addNewsletterDate">Newsletter date:</label>
                        <input type="text" name="addNewsletterDate" id="addNewsletterDate" autocomplete="off">
                    </div>
                    
                    <div class='width-100'>
                        <label id="newsletterFile-label" for="addNewsletterFile">Choose file to upload</label>
                        <input type="file" id="addNewsletterFile" name="addNewsletterFile" required>
                    </div>

                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue medium left" data-text="Add newsletter"><span>Add newsletter</span></button>
                        <button type="button" class="modal-btn btn-red medium close-btn right" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
                
               
            </div>
            
        </div>
    </div>
</div>
<!-- end older-newsletters Modal -->

<!-- Delete Newsletters Modal -->
<div class="modal" id="delete-newsletter-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper">
            <?php 
                echo '<img class="events" src="'.$this->basePath() .'/img/icons/icon-bin.png" alt="" />';
            ?>
        </div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove Newsletters</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-newsletter'>You really want to delete the newsletter: <span></span></div>
                <form id="deleteNewsletterForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deleteNewsletterID" name="deleteNewsletterID" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end delete newsletters Modal -->

<!-- Event (detail) Modal -->
<div class="modal" id="show-event-modal">
<!--  <div class="modal-sandbox"></div>-->
  <div class="modal-box lg orange">
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
	    </div>
      	</div>
      	
        <div class="circle-img-wrapper"><img class="events" src="img/icons/icon-event-orange.png" alt="" /></div>
      	
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Event details</span>
      	</div>
      	
    	
    </div>
 
    <div class="modal-body">
        
	<div  class="modal-text">
            <div class="loader"></div>
            <label class='response-msg'></label>
            <table id='eventBox' class="event-list">
		<tr>
                    <td id="color-box" class="date">
			<div class="day" id="eventDay"></div>
			<div class="month_year_wrapper">
                            <div class="month" id="eventMonth"></div>
                            <div class="year" id="eventYear"></div>
			</div>
                    </td>
                    <td id='event-details' class="content">
			<div class="title"></div>
                        
                        <?php if ($this->access('event.edit')) { ?>
                        <div class="admin-option">
                            <a href="#" class="tooltip modal-trigger-edit-event-details" data-modal="edit-event-modal" data-id="" data-title="" data-eventDate="" data-location="" data-content="">
                                <button class="btn-admin">
                                    <img class="icon-list" src="img/icons/icon-edit-blue.png" >
                                </button>
                                <span class="tooltiptext edit">Edit</span>
                            </a>
                            <a href="#" class="tooltip modal-trigger-delete-event-details" data-modal="delete-event-modal" data-id="" data-title="">
                                <button class="btn-admin">
                                    <img class="icon-list" src="img/icons/icon-bin-red.png" >
                                </button>
                                <span class="tooltiptext remove">Remove</span>
                            </a>
                        </div>
                        <?php } ?>
                        
                        
                        <div class="location">Location: <span></span></div>
			<div class="text"></div>
                    </td>
                    
		</tr>
            </table>
        </div>
        
	<div class="btn-modal-box">
            <button type="button" class="modal-btn btn-orange small close-btn" data-text="Close"><span>Close</span></button>
	</div> 
    </div> 
  </div>
</div>
<!-- end Events-detail Modal -->

<!-- Events-List Modal -->
<div class="modal" id="events-list">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg orange"> 
        <div class="modal-header photo">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="events" src="img/icons/icon-event-orange.png" alt="" /></div>
      	
            <!-- original version -->
            <!-- <div class="modal-title">
                    <span>About us</span>
            </div> -->
      	
            <!-- img version -->
            <img class="bg-img" src="img/events/events-list.jpg"/>
            <div class="cut-box">	
                <div class="modal-title">
                    <span>Events list</span>
                </div>
                <div class="modal-title-cut"></div>
            </div>
            <!-- end img version -->	
        </div>
 
    
        <div class="modal-body">
    
            <div class="modal-text">
		<table class="event-list">
                
                <?php 
                     
                    $colorBoxList = array("red-box","purpure-box","blue-box","orange-box","green-box", "yellow-box", "brown-box");
                    $countColorList = 0;
                    
                    if(empty($this->schoolEvents)){
                        echo '<div class="modal-no-content">';
                                echo '<div class="modal-info-wrapper">';
                                    echo '<img src="img/icons/icon-drum.png"/>';
                                    echo '<span>No events scheduled yet ...</span>';
                                echo '</div>';
                        echo '</div>';
                    }else{
                    
                        foreach ($this->schoolEvents  as $event) :
                            $dateEvent = date_parse($event->getDateEvent());
                            $monthEvent = date("M", mktime(0, 0, 0, $dateEvent['month'], 10));

                            echo '<tr>';

                                echo '<td id="'.$colorBoxList[$countColorList].'" class="date">'
                                    . '<div class="day">'.($dateEvent['day']<10?("0".$dateEvent['day']):$dateEvent['day']).'</div>'
                                    . '<div class="month_year_wrapper">'
                                        . '<div class="month">'.$monthEvent.'</div>'
                                        . '<div class="year">'.$dateEvent['year'].'</div>'
                                    . '</div>'
                                    . '</td>'
                                    . ' <td class="content">'
                                        . '<div class="title">'.$event->getTitle().'</div>';

                                        echo '<div class="admin-option">';
                                            if ($this->access('event.edit')) { 
                                            echo '<a href="#" class="tooltip modal-trigger-edit-event" data-modal="edit-event-modal" data-eventID="'.$event->getId().'" data-eventTitle="'.$event->getTitle().'" data-eventYear="'.$dateEvent['year'].'" data-eventMonth="'.($dateEvent['month']-1).'" data-eventDay="'.$dateEvent['day'].'" data-eventLocation="'.$event->getLocation().'" data-eventContent="'.$event->getContent().'" >'
                                                    . '<button class="btn-admin">'
                                                        . '<img class="icon-list" src="img/icons/icon-edit-blue.png" >'
                                                    . '</button>'
                                                    . '<span class="tooltiptext edit">Edit</span>'
                                                . '</a>';
                                            }
                                            if ($this->access('event.delete')) {
                                            echo '<a href="#" class="tooltip modal-trigger-delete-event" data-modal="delete-event-modal" data-id="'.$event->getId().'" data-title="'.$event->getTitle().'">'
                                                    . '<button class="btn-admin">'
                                                        . '<img class="icon-list" src="img/icons/icon-bin-red.png" >'
                                                    . '</button>'
                                                    . '<span class="tooltiptext remove">Remove</span>'
                                                . '</a>';
                                            }

                                        echo '</div>';

                                        if($event->getLocation() !== null){
                                            echo '<div class="location">Location: <span>'.$event->getLocation().'</span></div>';
                                        }
                                        echo '<div class="text">'.$event->getContent().'</div>'
                                    . '</td>';

                            echo '</tr>';
                            $countColorList ++;
                            if($countColorList > 6){
                                $countColorList = 0;
                            }

                        endforeach;
                    }
                    
                ?>
	
		</table>
            </div>
            <div class="btn-modal-box">
                <button type="button" class="modal-btn btn-orange small close-btn" data-text="Close"><span>Close</span></button>
            </div> 
        </div> 
    </div>
</div>
<!-- end Events-List Modal -->

<!-- Add Event Modal-->
<div class="modal" id="add-event-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="events" src="img/icons/icon-event2.png" alt="" /></div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Add event</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="addEventForm" class="cms" enctype="multipart/form-data"> 
                    
                    <div class='width-100'>
                        <label for="addEventTitle">Event title:</label>
                        <input type="text" id="addEventTitle" name="addEventTitle" required>
                    </div>
                    
                    <div class='width-30-left'>
                        <label for="addEventDate">Event date:</label>
                        <input type="text" name="addEventDate" id="addEventDate" autocomplete="off">
                    </div>
                    
                    <div class='width-60-right'>
                        <label for="addEventLocation">Event location:</label>
                        <input type="text" id="addEventLocation" name="addEventLocation">
                    </div>
                    
                    <div class='width-100'>
                        <label for="addEventContent">About event:</label>
                        <textarea id="addEventContent" name="addEventContent" rows="10"></textarea>
                    </div>
                    
                    <input type="hidden" id="addEventAuthorID" name="addEventAuthorID" required>
                    
                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Add event"><span>Add event</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Add Event Modal-->

<!-- Edit Event Modal-->
<div class="modal" id="edit-event-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="news-edit" src="img/icons/icon-edit.png" alt="" /></div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Edit event</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="editEventForm" class="cms" enctype="multipart/form-data">
                         
                    <input id="editEventID" name='editEventID' type="hidden">
                    
                    <div class='width-100'>
                        <label for="editEventTitle">Event title</label>
                        <input type="text" id="editEventTitle" name="editEventTitle" required>
                    </div>
                    
                    <div class='width-30-left'>
                        <label for="editEventDate">Event date:</label>
                        <input type="text" name="editEventDate" id="editEventDate" autocomplete="off">
                    </div>
                    
                    <div class='width-60-right'>
                        <label for="editEventLocation">Event location:</label>
                        <input type="text" id="editEventLocation" name="editEventLocation">
                    </div>
                    
                    <div class='width-100'>
                        <label for="editEventContent">About event:</label>
                        <textarea id="editEventContent" name="editEventContent" rows="10"></textarea>
                    </div>
                   
                    
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Save"><span>Save</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Cancel"><span>Cancel</span></button>
                    </div>
		</form>
               
            </div>
            
        </div>
    </div>
</div>
<!-- end Edit Event Modal-->

<!-- Delete Event Modal -->
<div class="modal" id="delete-event-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper">
            <?php 
                    echo '<img class="events" src="'.$this->basePath() .'/img/icons/icon-bin.png" alt="" />';
            ?>      
        </div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove Event</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-event'>You really want to delete the event: <span></span></div>
                <form id="deleteEventForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deleteEventID" name="deleteEventID" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end delete Event Modal -->

<!-- Manage Our Awards Modal -->
<div class="modal" id="manage-our-awards-modal">
<!--  <div class="modal-sandbox"></div>-->
  <div class="modal-box sm">
  
    <div class="modal-header">
      	<div class="close-modal">
	    <div class="close-modal-inner">
	    	<label>close</label>
            </div>
      	</div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-settings.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Our Awards</span>
      	</div>
    </div>
 
    <div class="modal-body">
    
        <div class="modal-text">
            <div class="btn-modal-box our-team-add">
                <button class="modal-trigger-add-our-awards btn-max btn-red reversed" data-modal="add-our-awards-modal" data-text="Add award">
                    <span><i class="fa fa-plus"></i>Add award</span>
                </button>
            </div>
            <hr class="burgundy" />
            
            
            <div class="table-header">List of awards</div>
            <div class="small-table">    
                <?php 
                    foreach($this->ourAwards as $award){
                        
                        
                            echo '<div class="small-table-row">';

                                echo '<div class="small-table-cell long-title">';
                                    echo '<span>'.$award->getTitle().'</span>';
                                echo '</div>';

                                echo '<div class="small-table-cell remove">';
                                    if ($this->access('award.delete')) {
                                        echo '<a href="#" class="modal-trigger-delete-our-awards tooltip" data-modal="delete-our-awards-modal" data-id="'.$award->getId().'" data-title="'.$award->getTitle().'">';
                                            echo '<button class="btn-admin">';
                                                echo '<img class="icon-list" src="img/icons/icon-bin-red.png" >';
                                            echo '</button>';
                                            echo '<span class="tooltiptext remove">Remove</span>';
                                        echo '</a>';
                                    }                               
                                echo '</div>';

                            echo '</div>';
                        

                    }
                ?>
            </div>
            
            <hr class="burgundy" />
            
          
        </div>      
        <div class="btn-modal-box">
            <button type="button" class="modal-btn small btn-burgundy close-btn" data-text="Close"><span>Close</span></button>
        </div> 
	
	
    </div> 
  </div>
</div>
<!-- end Our Awards Modal -->

<!-- Add Our Awards Modal -->
<div class="modal" id="add-our-awards-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper"><img class="events" src="img/icons/icon-award.png" alt="" /></div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Add New Award</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <form id="addOurAwardForm" class="cms" enctype="multipart/form-data">
                    
                    <label id="ourAwardTitle-label" for="addOurAwardTitle">Award title</label>
                    <input type="text" id="addOurAwardTitle" name="addOurAwardTitle" required>
                    
                    <label id="ourAwardFile-label" for="addOurAwardFile">Choose file to upload</label>
                    <input type="file" id="addOurAwardFile" name="addOurAwardFile" required>

                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue medium left" data-text="Add award"><span>Add award</span></button>
                        <button type="button" class="modal-btn btn-red medium close-btn right" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
                
               
            </div>
            
        </div>
    </div>
</div>
<!-- end oAdd Our Awards Modal -->

<!-- Delete Our Award Modal -->
<div class="modal" id="delete-our-awards-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper">
            <?php 
                echo '<img class="events" src="'.$this->basePath() .'/img/icons/icon-bin.png" alt="" />';
            ?>          
        </div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove Award</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-our-award'>You really want to delete the aword: <span></span></div>
                <form id="deleteOurAwardForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="ourAwardID" name="ourAwardID" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end delete Our Award Modal -->

<!-- Edit Gallery Modal-->
<div class="modal" id="edit-gallery-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            
            <div class="circle-img-wrapper">
                <?php 
                    echo '<img class="news-edit" src="'.$this->basePath() .'/img/icons/icon-edit.png" alt="" />';
                ?>   
            </div>

            <!-- original version -->
            <div class="modal-title">
                    <span>Edit gallery</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="editGalleryForm" class="cms" enctype="multipart/form-data">
                    <input id="editGalleryID" name='editGalleryID' type="hidden" required>
                    <input id="editGalleryAuthorID" name='editGalleryAuthorID' type="hidden" required>

                    <div class='width-60-left'>
                        <label for="editGalleryTitle">Gallery title</label>
                        <input type="text" id="editGalleryTitle" name="editGalleryTitle" required>
                    </div>
                    
                    <div class='width-35-right'>
                        <label id='editGalleryVideoLabel'>Add video:</label>
                        <input type="file" id="editGalleryVideo" name="editGalleryVideo">
                    </div>
                    <div class='width-35-right'>
                        <label id='editGalleryVideoLabel_current'>Current video:</label>
                        <table id='editGalleryVideo_current'>
                            <tr>
                                <td class="icon"><img class="icon" src="img/icons/icon-video.png"></td>
                                <td class="text" id='editGalleryVideoTitle'></td>
                                <td class="option">
                                    <label class="preview-video-label" id="preview-video-edit-gallery-label">
                                        <a href="#" class="remove_field_video" id='remove_field_video'>X</a>
                                    </label>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <input type="checkbox" class='to_remove' id='edit_gallery_remove_video'>
                    
                    <div class='width-100'>
                        <label for="editGalleryContent">Gallery description (text):</label>
                        <textarea id="editGalleryContent" name="editGalleryContent" rows="10"></textarea>
                    </div>


                    <div class='width-100'>
                        <label for="current_gallery_wrap" id="current_gallery_wrap_label">Current gallery:</label>
                        <div class="current_gallery_wrap" id="current_gallery_wrap">
    <!--                       CURRENT GALLERY-->                       
                        </div>

                        <ul class="to_remove" id="picture_to_remove_from_gallery">
    <!--                       list of current picture removed-->
                        </ul>

                        <div class="btn-modal-box">
                            <button id='add-photo-gallery-button-edit' class="btn-add-user btn-burgundy reversed" data-text="Add some photo(s)"><span>Add some photo(s)</span></button>
                        </div>
                        
                        <label id="input_fields_wrap_edit_label">Selected photos:</label>
                        <div class="input_fields_wrap" id="input_fields_wrap_edit">
                            
    <!--                        ADDED PHOTO GALLERY-->
                        </div>
                    </div>

                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Edit gallery"><span>Edit gallery</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
               
            </div>
                   
        </div>
    </div>
</div>
<!-- end Edit Gallery Modal-->

<!-- Delete galleryPost Modal -->
<div class="modal" id="delete-gallery-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper">
            <?php 
                echo '<img class="events" src="'.$this->basePath() .'/img/icons/icon-bin.png" alt="" />';
            ?> 
        </div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove gallery</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-gallery'>You really want to delete gallery: <span></span></div>
                <form id="deleteGalleryForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deleteGalleryID" name="deletePostID" required>
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end delete galleryPost Modal -->


<!-- Edit Post Modal-->
<div class="modal" id="edit-post-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <?php 
                echo '<div class="circle-img-wrapper"><img class="news-edit" src="'.$this->basePath() .'/img/icons/icon-edit.png" alt="" /></div>';
                               
            ?>  
            

            <!-- original version -->
            <div class="modal-title">
                    <span>Edit post</span>
            </div>
	
        </div>
        <div class="modal-body">
            
            <div class="modal-text">
                
                <label class='response-msg'></label>
                <div class="loader"></div>
                
                <form id="editPostForm" class="cms" enctype="multipart/form-data">
                    <input id="editPostID" name='editPostID' type="hidden" required>
                    <input type="hidden" id="editPost_teacherID" name="editPost_teacherID" required />
                    <input type="hidden" id="editPost_learningSupportID" name="editPost_learningSupportID"/>
                    <input type="hidden" id="editPost_authorID" name="editPost_authorID" required/>
                    
                    <label for="editPostTitle">Post title</label>
                    <input type="text" id="editPostTitle" name="editPostTitle" required>
                    
                    <label for="editPostContent">Post (text):</label>
                    <textarea id="editPostContent" name="editPostContent" rows="10"></textarea>

                    
                    <div class='width-50-left'>
                        <label id='editPostDocLabel_current'>Current document:</label>
                        <label id='editPostDocLabel'>Add document:</label>
                        <table id='editPostDoc_current'>
                            <tr>
                                <td class="icon"><img class="icon" src="img/icons/icon-document.png"></td>
                                <td class="text" id='editPostDocTitle'></td>
                                <td class="option">
                                    <label class="preview-doc-label" id="preview-doc-edit-post-label_current">
                                        <a href="#" class="input-X-button">X</a>
                                    </label>
                                </td>
                            </tr>
                        </table>
                        
                        <label class='input-X-button' id='preview-doc-edit-post-label'><a href='#'>X</a></label>
                        <input type="file" id="editPostDoc" name="editPostDoc">
                        <input type="checkbox" class='to_remove' id='edit_post_remove_doc'>
                    </div> 
                    
                    
                    <div class='width-50-right'>
                        <label id='editPostVideoLabel_current'>Current video:</label>
                        <label id='editPostVideoLabel'>Add video:</label>
                        <table id='editPostVideo_current'>
                            <tr>
                                <td class="icon"><img class="icon" src="img/icons/icon-video.png"></td>
                                <td class="text" id='editPostVideoTitle'></td>
                                <td class="option">
                                    <label class="preview-video-label" id="preview-video-edit-post-label_current">
                                        <a href="#" class="input-X-button">X</a>
                                    </label>
                                </td>
                            </tr>
                        </table>
                        
                        <label class='input-X-button' id='preview-video-edit-post-label'><a href='#'>X</a></label>
                        <input type="file" id="editPostVideo" name="editPostVideo">
                        <input type="checkbox" class='to_remove' id='edit_post_remove_video'>
                    </div>      
                    
                    <div class='width-100'>
                        <label for="current_gallery_wrap_class_post" id="current_gallery_wrap_class_post_label">Current gallery:</label>
                        <div class="current_gallery_wrap" id="current_gallery_wrap_class_post">
    <!--                       CURRENT GALLERY-->                       
                        </div>

                        <ul class="to_remove" id="picture_to_remove_from_post">
    <!--                       list of current picture removed-->
                        </ul>

                        <div class="btn-modal-box">
                            <button id='add-photo-gallery-button-edit-class-post' class="btn-add-user btn-burgundy reversed" data-text="Add some photo(s)"><span>Add some photo(s)</span></button>
                        </div>
                        
                        <label id="input_fields_wrap_edit_class_post_label">Selected photos:</label>
                        <div class="input_fields_wrap" id="input_fields_wrap_edit_class_post">
                            
    <!--                        ADDED PHOTO GALLERY-->
                        </div>
                    </div>

                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-blue left" data-text="Save"><span>Save</span></button>
                        <button type="button" class="modal-btn btn-red close-btn right" data-text="Discard"><span>Discard</span></button>
                    </div>
		</form>
               
            </div>
                   
        </div>
    </div>
</div>
<!-- end Edit Post Modal-->

<!-- Delete Post Modal -->
<div class="modal" id="delete-post-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box sm">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
	    	<label>close</label>
                </div>
            </div>
      	<div class="circle-img-wrapper">
            <?php 
                echo '<img class="events" src="'.$this->basePath() .'/img/icons/icon-bin.png" alt="" />';
            ?>  
        </div>
      	<!-- original version -->
      	<div class="modal-title">
      		<span>Remove Post</span>
      	</div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <label class='response-msg'></label>
                <div class="loader"></div>
                <div class='confirmation-question' id='confirmation-question-post'>You really want to delete post: <span></span></div>
                <form id="deletePostForm" class="cms" enctype="multipart/form-data">
                    <input type="hidden" id="deletePostID" name="deletePostID" required>
                    <input type="hidden" id="deleteTeacherID" name="deleteTeacherID" required>
                    <input type="hidden" id="deleteLearningSupportID" name="deleteLearningSupportID">
                    <div class="btn-modal-box">
                        <button type="submit" class="modal-btn btn-green medium reversed left" data-text="Yes"><span><i class="fa fa-check-circle-o fa-lg" aria-hidden="true"></i> Yes</span></button>
                        <button type="button" class="modal-btn btn-red medium reversed close-btn right" data-text="No"><span><i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>No</span></button>
                    </div>
                </form>
   
            </div>
            
        </div>
    </div>
</div>
<!-- end delete post Modal -->

<!-- Show Video Modal-->
<div class="modal" id="show-video-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box lg video">
        <div class="modal-header">
            <div class="close-modal">
                <div class="close-modal-inner">
                    <label>close</label>
                </div>
            </div>
            <div class="circle-img-wrapper"><img class="video" src="img/icons/icon-video.png" alt="" /></div>
            <div class="modal-title">
                    <span>Watch the video</span>
            </div>
	
        </div>
        <div class="modal-body">
            <video controls id='post-video'></video>        
        </div>
    </div>
</div>
<!-- end Show Video Modal-->

<!-- Error Post Modal -->
<div class="modal" id="error-post-modal">
<!--    <div class="modal-sandbox"></div>-->
    <div class="modal-box red sm">
        <div class="modal-header">
            <div class="modal-title">
                    <span>Error</span>
            </div>
        </div>
        
        
        <div class="modal-body">
            
            <div class="modal-text">
                <div class='confirmation-question' id='error-input-file'></div>
                <div class='confirmation-question' id='error-description-input-file'><span class='error-description'></span></div>
                <hr class="red" />
                <button type="button" class="modal-btn btn-red small error-close-btn" data-text="OK"><span>OK</span></button>  
            </div>
            
        </div>
    </div>
</div>
<!-- end error post Modal -->

<!-- Scripts -->
    <!-- slider -->
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script type="text/javascript" src="https://jonthornton.github.io/jquery-timepicker/jquery.timepicker.js"></script>
    <script src="js/slider.js" type="text/javaScript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.news-box .school-news');
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>
    <script src="js/summernote/summernote-options.js" type="text/javaScript"></script>
    <!-- subscribe -->
<!--    <script src="js/subscribe.js" type="text/javaScript"></script>   -->
    <script src="js/welcome-msg-edit.js" type="text/javaScript"></script>
    <script src="js/about-us-edit.js" type="text/javaScript"></script>
    <script src="js/news-add-02.js" type="text/javaScript"></script>
    <script src="js/news-edit-02.js" type="text/javaScript"></script>
    <script src="js/news-delete.js" type="text/javaScript"></script>
    <script src="js/event-add-01.js" type="text/javaScript"></script>
    <script src="js/event-edit-01.js" type="text/javaScript"></script>
    <script src="js/event-delete.js" type="text/javaScript"></script>
    <script src="js/date-picker.js" type="text/javaScript"></script>
    
    <script src="js/calendar.js" type="text/javaScript"></script>
    <script src="js/newsletter-add-01.js" type="text/javaScript"></script>
    <script src="js/newsletter-delete.js" type="text/javaScript"></script>
    <script src="js/our-awards-add-01.js" type="text/javaScript"></script>
    <script src="js/our-awards-delete.js" type="text/javaScript"></script>
    
    <script src="js/gallery-edit.js" type="text/javaScript"></script>
    <script src="js/gallery-delete.js" type="text/javaScript"></script>
    <script src="js/show-video.js" type="text/javaScript"></script>
    
    <script src="js/post-edit-03.js" type="text/javaScript"></script>
    <script src="js/post-delete.js" type="text/javaScript"></script>



   